package wallettemplate.utils;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: config.proto

public final class ProtoConfig {
  private ProtoConfig() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AuthenticatorOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional bool paired = 1;
    /**
     * <code>optional bool paired = 1;</code>
     *
     * <pre>
     * Whether or not the wallet is paired. This will be set to repeated when multi-account is finished.
     * </pre>
     */
    boolean hasPaired();
    /**
     * <code>optional bool paired = 1;</code>
     *
     * <pre>
     * Whether or not the wallet is paired. This will be set to repeated when multi-account is finished.
     * </pre>
     */
    boolean getPaired();
  }
  /**
   * Protobuf type {@code Authenticator}
   */
  public static final class Authenticator extends
      com.google.protobuf.GeneratedMessage
      implements AuthenticatorOrBuilder {
    // Use Authenticator.newBuilder() to construct.
    private Authenticator(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Authenticator(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Authenticator defaultInstance;
    public static Authenticator getDefaultInstance() {
      return defaultInstance;
    }

    public Authenticator getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Authenticator(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              paired_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoConfig.internal_static_Authenticator_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoConfig.internal_static_Authenticator_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtoConfig.Authenticator.class, ProtoConfig.Authenticator.Builder.class);
    }

    public static com.google.protobuf.Parser<Authenticator> PARSER =
        new com.google.protobuf.AbstractParser<Authenticator>() {
      public Authenticator parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Authenticator(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Authenticator> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional bool paired = 1;
    public static final int PAIRED_FIELD_NUMBER = 1;
    private boolean paired_;
    /**
     * <code>optional bool paired = 1;</code>
     *
     * <pre>
     * Whether or not the wallet is paired. This will be set to repeated when multi-account is finished.
     * </pre>
     */
    public boolean hasPaired() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bool paired = 1;</code>
     *
     * <pre>
     * Whether or not the wallet is paired. This will be set to repeated when multi-account is finished.
     * </pre>
     */
    public boolean getPaired() {
      return paired_;
    }

    private void initFields() {
      paired_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, paired_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, paired_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ProtoConfig.Authenticator parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoConfig.Authenticator parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoConfig.Authenticator parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoConfig.Authenticator parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoConfig.Authenticator parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ProtoConfig.Authenticator parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ProtoConfig.Authenticator parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ProtoConfig.Authenticator parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ProtoConfig.Authenticator parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ProtoConfig.Authenticator parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ProtoConfig.Authenticator prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Authenticator}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ProtoConfig.AuthenticatorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoConfig.internal_static_Authenticator_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoConfig.internal_static_Authenticator_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoConfig.Authenticator.class, ProtoConfig.Authenticator.Builder.class);
      }

      // Construct using ProtoConfig.Authenticator.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        paired_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoConfig.internal_static_Authenticator_descriptor;
      }

      public ProtoConfig.Authenticator getDefaultInstanceForType() {
        return ProtoConfig.Authenticator.getDefaultInstance();
      }

      public ProtoConfig.Authenticator build() {
        ProtoConfig.Authenticator result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ProtoConfig.Authenticator buildPartial() {
        ProtoConfig.Authenticator result = new ProtoConfig.Authenticator(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.paired_ = paired_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoConfig.Authenticator) {
          return mergeFrom((ProtoConfig.Authenticator)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtoConfig.Authenticator other) {
        if (other == ProtoConfig.Authenticator.getDefaultInstance()) return this;
        if (other.hasPaired()) {
          setPaired(other.getPaired());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtoConfig.Authenticator parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtoConfig.Authenticator) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional bool paired = 1;
      private boolean paired_ ;
      /**
       * <code>optional bool paired = 1;</code>
       *
       * <pre>
       * Whether or not the wallet is paired. This will be set to repeated when multi-account is finished.
       * </pre>
       */
      public boolean hasPaired() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bool paired = 1;</code>
       *
       * <pre>
       * Whether or not the wallet is paired. This will be set to repeated when multi-account is finished.
       * </pre>
       */
      public boolean getPaired() {
        return paired_;
      }
      /**
       * <code>optional bool paired = 1;</code>
       *
       * <pre>
       * Whether or not the wallet is paired. This will be set to repeated when multi-account is finished.
       * </pre>
       */
      public Builder setPaired(boolean value) {
        bitField0_ |= 0x00000001;
        paired_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool paired = 1;</code>
       *
       * <pre>
       * Whether or not the wallet is paired. This will be set to repeated when multi-account is finished.
       * </pre>
       */
      public Builder clearPaired() {
        bitField0_ = (bitField0_ & ~0x00000001);
        paired_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Authenticator)
    }

    static {
      defaultInstance = new Authenticator(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Authenticator)
  }

  public interface ReceiveAddressesOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated string pubkey = 1;
    /**
     * <code>repeated string pubkey = 1;</code>
     *
     * <pre>
     * An array of (min 10) hex encoded public keys that will be loaded in the receive pane.
     * </pre>
     */
    java.util.List<java.lang.String>
    getPubkeyList();
    /**
     * <code>repeated string pubkey = 1;</code>
     *
     * <pre>
     * An array of (min 10) hex encoded public keys that will be loaded in the receive pane.
     * </pre>
     */
    int getPubkeyCount();
    /**
     * <code>repeated string pubkey = 1;</code>
     *
     * <pre>
     * An array of (min 10) hex encoded public keys that will be loaded in the receive pane.
     * </pre>
     */
    java.lang.String getPubkey(int index);
    /**
     * <code>repeated string pubkey = 1;</code>
     *
     * <pre>
     * An array of (min 10) hex encoded public keys that will be loaded in the receive pane.
     * </pre>
     */
    com.google.protobuf.ByteString
        getPubkeyBytes(int index);
  }
  /**
   * Protobuf type {@code ReceiveAddresses}
   */
  public static final class ReceiveAddresses extends
      com.google.protobuf.GeneratedMessage
      implements ReceiveAddressesOrBuilder {
    // Use ReceiveAddresses.newBuilder() to construct.
    private ReceiveAddresses(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReceiveAddresses(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReceiveAddresses defaultInstance;
    public static ReceiveAddresses getDefaultInstance() {
      return defaultInstance;
    }

    public ReceiveAddresses getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReceiveAddresses(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                pubkey_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              pubkey_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          pubkey_ = new com.google.protobuf.UnmodifiableLazyStringList(pubkey_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoConfig.internal_static_ReceiveAddresses_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoConfig.internal_static_ReceiveAddresses_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtoConfig.ReceiveAddresses.class, ProtoConfig.ReceiveAddresses.Builder.class);
    }

    public static com.google.protobuf.Parser<ReceiveAddresses> PARSER =
        new com.google.protobuf.AbstractParser<ReceiveAddresses>() {
      public ReceiveAddresses parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReceiveAddresses(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReceiveAddresses> getParserForType() {
      return PARSER;
    }

    // repeated string pubkey = 1;
    public static final int PUBKEY_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList pubkey_;
    /**
     * <code>repeated string pubkey = 1;</code>
     *
     * <pre>
     * An array of (min 10) hex encoded public keys that will be loaded in the receive pane.
     * </pre>
     */
    public java.util.List<java.lang.String>
        getPubkeyList() {
      return pubkey_;
    }
    /**
     * <code>repeated string pubkey = 1;</code>
     *
     * <pre>
     * An array of (min 10) hex encoded public keys that will be loaded in the receive pane.
     * </pre>
     */
    public int getPubkeyCount() {
      return pubkey_.size();
    }
    /**
     * <code>repeated string pubkey = 1;</code>
     *
     * <pre>
     * An array of (min 10) hex encoded public keys that will be loaded in the receive pane.
     * </pre>
     */
    public java.lang.String getPubkey(int index) {
      return pubkey_.get(index);
    }
    /**
     * <code>repeated string pubkey = 1;</code>
     *
     * <pre>
     * An array of (min 10) hex encoded public keys that will be loaded in the receive pane.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPubkeyBytes(int index) {
      return pubkey_.getByteString(index);
    }

    private void initFields() {
      pubkey_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < pubkey_.size(); i++) {
        output.writeBytes(1, pubkey_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < pubkey_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(pubkey_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getPubkeyList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ProtoConfig.ReceiveAddresses parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoConfig.ReceiveAddresses parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoConfig.ReceiveAddresses parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoConfig.ReceiveAddresses parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoConfig.ReceiveAddresses parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ProtoConfig.ReceiveAddresses parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ProtoConfig.ReceiveAddresses parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ProtoConfig.ReceiveAddresses parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ProtoConfig.ReceiveAddresses parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ProtoConfig.ReceiveAddresses parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ProtoConfig.ReceiveAddresses prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ReceiveAddresses}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ProtoConfig.ReceiveAddressesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoConfig.internal_static_ReceiveAddresses_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoConfig.internal_static_ReceiveAddresses_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoConfig.ReceiveAddresses.class, ProtoConfig.ReceiveAddresses.Builder.class);
      }

      // Construct using ProtoConfig.ReceiveAddresses.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        pubkey_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoConfig.internal_static_ReceiveAddresses_descriptor;
      }

      public ProtoConfig.ReceiveAddresses getDefaultInstanceForType() {
        return ProtoConfig.ReceiveAddresses.getDefaultInstance();
      }

      public ProtoConfig.ReceiveAddresses build() {
        ProtoConfig.ReceiveAddresses result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ProtoConfig.ReceiveAddresses buildPartial() {
        ProtoConfig.ReceiveAddresses result = new ProtoConfig.ReceiveAddresses(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          pubkey_ = new com.google.protobuf.UnmodifiableLazyStringList(
              pubkey_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.pubkey_ = pubkey_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoConfig.ReceiveAddresses) {
          return mergeFrom((ProtoConfig.ReceiveAddresses)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtoConfig.ReceiveAddresses other) {
        if (other == ProtoConfig.ReceiveAddresses.getDefaultInstance()) return this;
        if (!other.pubkey_.isEmpty()) {
          if (pubkey_.isEmpty()) {
            pubkey_ = other.pubkey_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePubkeyIsMutable();
            pubkey_.addAll(other.pubkey_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtoConfig.ReceiveAddresses parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtoConfig.ReceiveAddresses) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated string pubkey = 1;
      private com.google.protobuf.LazyStringList pubkey_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensurePubkeyIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          pubkey_ = new com.google.protobuf.LazyStringArrayList(pubkey_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string pubkey = 1;</code>
       *
       * <pre>
       * An array of (min 10) hex encoded public keys that will be loaded in the receive pane.
       * </pre>
       */
      public java.util.List<java.lang.String>
          getPubkeyList() {
        return java.util.Collections.unmodifiableList(pubkey_);
      }
      /**
       * <code>repeated string pubkey = 1;</code>
       *
       * <pre>
       * An array of (min 10) hex encoded public keys that will be loaded in the receive pane.
       * </pre>
       */
      public int getPubkeyCount() {
        return pubkey_.size();
      }
      /**
       * <code>repeated string pubkey = 1;</code>
       *
       * <pre>
       * An array of (min 10) hex encoded public keys that will be loaded in the receive pane.
       * </pre>
       */
      public java.lang.String getPubkey(int index) {
        return pubkey_.get(index);
      }
      /**
       * <code>repeated string pubkey = 1;</code>
       *
       * <pre>
       * An array of (min 10) hex encoded public keys that will be loaded in the receive pane.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getPubkeyBytes(int index) {
        return pubkey_.getByteString(index);
      }
      /**
       * <code>repeated string pubkey = 1;</code>
       *
       * <pre>
       * An array of (min 10) hex encoded public keys that will be loaded in the receive pane.
       * </pre>
       */
      public Builder setPubkey(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePubkeyIsMutable();
        pubkey_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string pubkey = 1;</code>
       *
       * <pre>
       * An array of (min 10) hex encoded public keys that will be loaded in the receive pane.
       * </pre>
       */
      public Builder addPubkey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePubkeyIsMutable();
        pubkey_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string pubkey = 1;</code>
       *
       * <pre>
       * An array of (min 10) hex encoded public keys that will be loaded in the receive pane.
       * </pre>
       */
      public Builder addAllPubkey(
          java.lang.Iterable<java.lang.String> values) {
        ensurePubkeyIsMutable();
        super.addAll(values, pubkey_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string pubkey = 1;</code>
       *
       * <pre>
       * An array of (min 10) hex encoded public keys that will be loaded in the receive pane.
       * </pre>
       */
      public Builder clearPubkey() {
        pubkey_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string pubkey = 1;</code>
       *
       * <pre>
       * An array of (min 10) hex encoded public keys that will be loaded in the receive pane.
       * </pre>
       */
      public Builder addPubkeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePubkeyIsMutable();
        pubkey_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ReceiveAddresses)
    }

    static {
      defaultInstance = new ReceiveAddresses(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ReceiveAddresses)
  }

  public interface AddressBookOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string address = 1;
    /**
     * <code>optional string address = 1;</code>
     *
     * <pre>
     * This is a placeholder for the address book.
     * </pre>
     */
    boolean hasAddress();
    /**
     * <code>optional string address = 1;</code>
     *
     * <pre>
     * This is a placeholder for the address book.
     * </pre>
     */
    java.lang.String getAddress();
    /**
     * <code>optional string address = 1;</code>
     *
     * <pre>
     * This is a placeholder for the address book.
     * </pre>
     */
    com.google.protobuf.ByteString
        getAddressBytes();
  }
  /**
   * Protobuf type {@code AddressBook}
   */
  public static final class AddressBook extends
      com.google.protobuf.GeneratedMessage
      implements AddressBookOrBuilder {
    // Use AddressBook.newBuilder() to construct.
    private AddressBook(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AddressBook(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AddressBook defaultInstance;
    public static AddressBook getDefaultInstance() {
      return defaultInstance;
    }

    public AddressBook getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AddressBook(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              address_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoConfig.internal_static_AddressBook_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoConfig.internal_static_AddressBook_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtoConfig.AddressBook.class, ProtoConfig.AddressBook.Builder.class);
    }

    public static com.google.protobuf.Parser<AddressBook> PARSER =
        new com.google.protobuf.AbstractParser<AddressBook>() {
      public AddressBook parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AddressBook(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AddressBook> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string address = 1;
    public static final int ADDRESS_FIELD_NUMBER = 1;
    private java.lang.Object address_;
    /**
     * <code>optional string address = 1;</code>
     *
     * <pre>
     * This is a placeholder for the address book.
     * </pre>
     */
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string address = 1;</code>
     *
     * <pre>
     * This is a placeholder for the address book.
     * </pre>
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          address_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string address = 1;</code>
     *
     * <pre>
     * This is a placeholder for the address book.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      address_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getAddressBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getAddressBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ProtoConfig.AddressBook parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoConfig.AddressBook parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoConfig.AddressBook parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoConfig.AddressBook parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoConfig.AddressBook parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ProtoConfig.AddressBook parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ProtoConfig.AddressBook parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ProtoConfig.AddressBook parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ProtoConfig.AddressBook parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ProtoConfig.AddressBook parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ProtoConfig.AddressBook prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AddressBook}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ProtoConfig.AddressBookOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoConfig.internal_static_AddressBook_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoConfig.internal_static_AddressBook_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoConfig.AddressBook.class, ProtoConfig.AddressBook.Builder.class);
      }

      // Construct using ProtoConfig.AddressBook.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        address_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoConfig.internal_static_AddressBook_descriptor;
      }

      public ProtoConfig.AddressBook getDefaultInstanceForType() {
        return ProtoConfig.AddressBook.getDefaultInstance();
      }

      public ProtoConfig.AddressBook build() {
        ProtoConfig.AddressBook result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ProtoConfig.AddressBook buildPartial() {
        ProtoConfig.AddressBook result = new ProtoConfig.AddressBook(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.address_ = address_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoConfig.AddressBook) {
          return mergeFrom((ProtoConfig.AddressBook)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtoConfig.AddressBook other) {
        if (other == ProtoConfig.AddressBook.getDefaultInstance()) return this;
        if (other.hasAddress()) {
          bitField0_ |= 0x00000001;
          address_ = other.address_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtoConfig.AddressBook parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtoConfig.AddressBook) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string address = 1;
      private java.lang.Object address_ = "";
      /**
       * <code>optional string address = 1;</code>
       *
       * <pre>
       * This is a placeholder for the address book.
       * </pre>
       */
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string address = 1;</code>
       *
       * <pre>
       * This is a placeholder for the address book.
       * </pre>
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string address = 1;</code>
       *
       * <pre>
       * This is a placeholder for the address book.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string address = 1;</code>
       *
       * <pre>
       * This is a placeholder for the address book.
       * </pre>
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string address = 1;</code>
       *
       * <pre>
       * This is a placeholder for the address book.
       * </pre>
       */
      public Builder clearAddress() {
        bitField0_ = (bitField0_ & ~0x00000001);
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>optional string address = 1;</code>
       *
       * <pre>
       * This is a placeholder for the address book.
       * </pre>
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        address_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:AddressBook)
    }

    static {
      defaultInstance = new AddressBook(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:AddressBook)
  }

  public interface SettingsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string setting = 1;
    /**
     * <code>optional string setting = 1;</code>
     *
     * <pre>
     * This is a placeholder for the settings menu.
     * </pre>
     */
    boolean hasSetting();
    /**
     * <code>optional string setting = 1;</code>
     *
     * <pre>
     * This is a placeholder for the settings menu.
     * </pre>
     */
    java.lang.String getSetting();
    /**
     * <code>optional string setting = 1;</code>
     *
     * <pre>
     * This is a placeholder for the settings menu.
     * </pre>
     */
    com.google.protobuf.ByteString
        getSettingBytes();
  }
  /**
   * Protobuf type {@code Settings}
   */
  public static final class Settings extends
      com.google.protobuf.GeneratedMessage
      implements SettingsOrBuilder {
    // Use Settings.newBuilder() to construct.
    private Settings(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Settings(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Settings defaultInstance;
    public static Settings getDefaultInstance() {
      return defaultInstance;
    }

    public Settings getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Settings(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              setting_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoConfig.internal_static_Settings_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoConfig.internal_static_Settings_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtoConfig.Settings.class, ProtoConfig.Settings.Builder.class);
    }

    public static com.google.protobuf.Parser<Settings> PARSER =
        new com.google.protobuf.AbstractParser<Settings>() {
      public Settings parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Settings(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Settings> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string setting = 1;
    public static final int SETTING_FIELD_NUMBER = 1;
    private java.lang.Object setting_;
    /**
     * <code>optional string setting = 1;</code>
     *
     * <pre>
     * This is a placeholder for the settings menu.
     * </pre>
     */
    public boolean hasSetting() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string setting = 1;</code>
     *
     * <pre>
     * This is a placeholder for the settings menu.
     * </pre>
     */
    public java.lang.String getSetting() {
      java.lang.Object ref = setting_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          setting_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string setting = 1;</code>
     *
     * <pre>
     * This is a placeholder for the settings menu.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getSettingBytes() {
      java.lang.Object ref = setting_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        setting_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      setting_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getSettingBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getSettingBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ProtoConfig.Settings parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoConfig.Settings parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoConfig.Settings parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoConfig.Settings parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoConfig.Settings parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ProtoConfig.Settings parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ProtoConfig.Settings parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ProtoConfig.Settings parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ProtoConfig.Settings parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ProtoConfig.Settings parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ProtoConfig.Settings prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Settings}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ProtoConfig.SettingsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoConfig.internal_static_Settings_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoConfig.internal_static_Settings_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoConfig.Settings.class, ProtoConfig.Settings.Builder.class);
      }

      // Construct using ProtoConfig.Settings.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        setting_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoConfig.internal_static_Settings_descriptor;
      }

      public ProtoConfig.Settings getDefaultInstanceForType() {
        return ProtoConfig.Settings.getDefaultInstance();
      }

      public ProtoConfig.Settings build() {
        ProtoConfig.Settings result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ProtoConfig.Settings buildPartial() {
        ProtoConfig.Settings result = new ProtoConfig.Settings(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.setting_ = setting_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoConfig.Settings) {
          return mergeFrom((ProtoConfig.Settings)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtoConfig.Settings other) {
        if (other == ProtoConfig.Settings.getDefaultInstance()) return this;
        if (other.hasSetting()) {
          bitField0_ |= 0x00000001;
          setting_ = other.setting_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtoConfig.Settings parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtoConfig.Settings) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string setting = 1;
      private java.lang.Object setting_ = "";
      /**
       * <code>optional string setting = 1;</code>
       *
       * <pre>
       * This is a placeholder for the settings menu.
       * </pre>
       */
      public boolean hasSetting() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string setting = 1;</code>
       *
       * <pre>
       * This is a placeholder for the settings menu.
       * </pre>
       */
      public java.lang.String getSetting() {
        java.lang.Object ref = setting_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          setting_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string setting = 1;</code>
       *
       * <pre>
       * This is a placeholder for the settings menu.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getSettingBytes() {
        java.lang.Object ref = setting_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          setting_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string setting = 1;</code>
       *
       * <pre>
       * This is a placeholder for the settings menu.
       * </pre>
       */
      public Builder setSetting(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        setting_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string setting = 1;</code>
       *
       * <pre>
       * This is a placeholder for the settings menu.
       * </pre>
       */
      public Builder clearSetting() {
        bitField0_ = (bitField0_ & ~0x00000001);
        setting_ = getDefaultInstance().getSetting();
        onChanged();
        return this;
      }
      /**
       * <code>optional string setting = 1;</code>
       *
       * <pre>
       * This is a placeholder for the settings menu.
       * </pre>
       */
      public Builder setSettingBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        setting_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Settings)
    }

    static {
      defaultInstance = new Settings(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Settings)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Authenticator_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Authenticator_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ReceiveAddresses_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ReceiveAddresses_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_AddressBook_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AddressBook_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Settings_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Settings_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014config.proto\"\037\n\rAuthenticator\022\016\n\006paire" +
      "d\030\001 \001(\010\"\"\n\020ReceiveAddresses\022\016\n\006pubkey\030\001 " +
      "\003(\t\"\036\n\013AddressBook\022\017\n\007address\030\001 \001(\t\"\033\n\010S" +
      "ettings\022\017\n\007setting\030\001 \001(\tB\rB\013ProtoConfig"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Authenticator_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Authenticator_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Authenticator_descriptor,
              new java.lang.String[] { "Paired", });
          internal_static_ReceiveAddresses_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_ReceiveAddresses_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ReceiveAddresses_descriptor,
              new java.lang.String[] { "Pubkey", });
          internal_static_AddressBook_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_AddressBook_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_AddressBook_descriptor,
              new java.lang.String[] { "Address", });
          internal_static_Settings_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_Settings_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Settings_descriptor,
              new java.lang.String[] { "Setting", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
