package wallettemplate.utils;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: config.proto

public final class ProtoConfig {
  private ProtoConfig() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AuthenticatorOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional bool paired = 1;
    /**
     * <code>optional bool paired = 1;</code>
     *
     * <pre>
     * Whether or not the wallet is paired. This will be set to repeated when multi-account is finished.
     * </pre>
     */
    boolean hasPaired();
    /**
     * <code>optional bool paired = 1;</code>
     *
     * <pre>
     * Whether or not the wallet is paired. This will be set to repeated when multi-account is finished.
     * </pre>
     */
    boolean getPaired();

    // optional string mpubkey = 2;
    /**
     * <code>optional string mpubkey = 2;</code>
     *
     * <pre>
     *Master public key from Authenticator.
     * </pre>
     */
    boolean hasMpubkey();
    /**
     * <code>optional string mpubkey = 2;</code>
     *
     * <pre>
     *Master public key from Authenticator.
     * </pre>
     */
    java.lang.String getMpubkey();
    /**
     * <code>optional string mpubkey = 2;</code>
     *
     * <pre>
     *Master public key from Authenticator.
     * </pre>
     */
    com.google.protobuf.ByteString
        getMpubkeyBytes();

    // optional string chaincode = 3;
    /**
     * <code>optional string chaincode = 3;</code>
     *
     * <pre>
     *Chaincode from Authenticator.
     * </pre>
     */
    boolean hasChaincode();
    /**
     * <code>optional string chaincode = 3;</code>
     *
     * <pre>
     *Chaincode from Authenticator.
     * </pre>
     */
    java.lang.String getChaincode();
    /**
     * <code>optional string chaincode = 3;</code>
     *
     * <pre>
     *Chaincode from Authenticator.
     * </pre>
     */
    com.google.protobuf.ByteString
        getChaincodeBytes();

    // optional string GMCregID = 4;
    /**
     * <code>optional string GMCregID = 4;</code>
     *
     * <pre>
     *GCM ID from Authenticator.
     * </pre>
     */
    boolean hasGMCregID();
    /**
     * <code>optional string GMCregID = 4;</code>
     *
     * <pre>
     *GCM ID from Authenticator.
     * </pre>
     */
    java.lang.String getGMCregID();
    /**
     * <code>optional string GMCregID = 4;</code>
     *
     * <pre>
     *GCM ID from Authenticator.
     * </pre>
     */
    com.google.protobuf.ByteString
        getGMCregIDBytes();
  }
  /**
   * Protobuf type {@code Authenticator}
   */
  public static final class Authenticator extends
      com.google.protobuf.GeneratedMessage
      implements AuthenticatorOrBuilder {
    // Use Authenticator.newBuilder() to construct.
    private Authenticator(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Authenticator(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Authenticator defaultInstance;
    public static Authenticator getDefaultInstance() {
      return defaultInstance;
    }

    public Authenticator getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Authenticator(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              paired_ = input.readBool();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              mpubkey_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              chaincode_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              gMCregID_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoConfig.internal_static_Authenticator_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoConfig.internal_static_Authenticator_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtoConfig.Authenticator.class, ProtoConfig.Authenticator.Builder.class);
    }

    public static com.google.protobuf.Parser<Authenticator> PARSER =
        new com.google.protobuf.AbstractParser<Authenticator>() {
      public Authenticator parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Authenticator(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Authenticator> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional bool paired = 1;
    public static final int PAIRED_FIELD_NUMBER = 1;
    private boolean paired_;
    /**
     * <code>optional bool paired = 1;</code>
     *
     * <pre>
     * Whether or not the wallet is paired. This will be set to repeated when multi-account is finished.
     * </pre>
     */
    public boolean hasPaired() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bool paired = 1;</code>
     *
     * <pre>
     * Whether or not the wallet is paired. This will be set to repeated when multi-account is finished.
     * </pre>
     */
    public boolean getPaired() {
      return paired_;
    }

    // optional string mpubkey = 2;
    public static final int MPUBKEY_FIELD_NUMBER = 2;
    private java.lang.Object mpubkey_;
    /**
     * <code>optional string mpubkey = 2;</code>
     *
     * <pre>
     *Master public key from Authenticator.
     * </pre>
     */
    public boolean hasMpubkey() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string mpubkey = 2;</code>
     *
     * <pre>
     *Master public key from Authenticator.
     * </pre>
     */
    public java.lang.String getMpubkey() {
      java.lang.Object ref = mpubkey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mpubkey_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string mpubkey = 2;</code>
     *
     * <pre>
     *Master public key from Authenticator.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMpubkeyBytes() {
      java.lang.Object ref = mpubkey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mpubkey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string chaincode = 3;
    public static final int CHAINCODE_FIELD_NUMBER = 3;
    private java.lang.Object chaincode_;
    /**
     * <code>optional string chaincode = 3;</code>
     *
     * <pre>
     *Chaincode from Authenticator.
     * </pre>
     */
    public boolean hasChaincode() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string chaincode = 3;</code>
     *
     * <pre>
     *Chaincode from Authenticator.
     * </pre>
     */
    public java.lang.String getChaincode() {
      java.lang.Object ref = chaincode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          chaincode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string chaincode = 3;</code>
     *
     * <pre>
     *Chaincode from Authenticator.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getChaincodeBytes() {
      java.lang.Object ref = chaincode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        chaincode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string GMCregID = 4;
    public static final int GMCREGID_FIELD_NUMBER = 4;
    private java.lang.Object gMCregID_;
    /**
     * <code>optional string GMCregID = 4;</code>
     *
     * <pre>
     *GCM ID from Authenticator.
     * </pre>
     */
    public boolean hasGMCregID() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string GMCregID = 4;</code>
     *
     * <pre>
     *GCM ID from Authenticator.
     * </pre>
     */
    public java.lang.String getGMCregID() {
      java.lang.Object ref = gMCregID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          gMCregID_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string GMCregID = 4;</code>
     *
     * <pre>
     *GCM ID from Authenticator.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getGMCregIDBytes() {
      java.lang.Object ref = gMCregID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gMCregID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      paired_ = false;
      mpubkey_ = "";
      chaincode_ = "";
      gMCregID_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, paired_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMpubkeyBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getChaincodeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getGMCregIDBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, paired_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMpubkeyBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getChaincodeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getGMCregIDBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ProtoConfig.Authenticator parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoConfig.Authenticator parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoConfig.Authenticator parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoConfig.Authenticator parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoConfig.Authenticator parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ProtoConfig.Authenticator parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ProtoConfig.Authenticator parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ProtoConfig.Authenticator parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ProtoConfig.Authenticator parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ProtoConfig.Authenticator parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ProtoConfig.Authenticator prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Authenticator}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ProtoConfig.AuthenticatorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoConfig.internal_static_Authenticator_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoConfig.internal_static_Authenticator_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoConfig.Authenticator.class, ProtoConfig.Authenticator.Builder.class);
      }

      // Construct using ProtoConfig.Authenticator.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        paired_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        mpubkey_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        chaincode_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        gMCregID_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoConfig.internal_static_Authenticator_descriptor;
      }

      public ProtoConfig.Authenticator getDefaultInstanceForType() {
        return ProtoConfig.Authenticator.getDefaultInstance();
      }

      public ProtoConfig.Authenticator build() {
        ProtoConfig.Authenticator result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ProtoConfig.Authenticator buildPartial() {
        ProtoConfig.Authenticator result = new ProtoConfig.Authenticator(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.paired_ = paired_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.mpubkey_ = mpubkey_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.chaincode_ = chaincode_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.gMCregID_ = gMCregID_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoConfig.Authenticator) {
          return mergeFrom((ProtoConfig.Authenticator)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtoConfig.Authenticator other) {
        if (other == ProtoConfig.Authenticator.getDefaultInstance()) return this;
        if (other.hasPaired()) {
          setPaired(other.getPaired());
        }
        if (other.hasMpubkey()) {
          bitField0_ |= 0x00000002;
          mpubkey_ = other.mpubkey_;
          onChanged();
        }
        if (other.hasChaincode()) {
          bitField0_ |= 0x00000004;
          chaincode_ = other.chaincode_;
          onChanged();
        }
        if (other.hasGMCregID()) {
          bitField0_ |= 0x00000008;
          gMCregID_ = other.gMCregID_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtoConfig.Authenticator parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtoConfig.Authenticator) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional bool paired = 1;
      private boolean paired_ ;
      /**
       * <code>optional bool paired = 1;</code>
       *
       * <pre>
       * Whether or not the wallet is paired. This will be set to repeated when multi-account is finished.
       * </pre>
       */
      public boolean hasPaired() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bool paired = 1;</code>
       *
       * <pre>
       * Whether or not the wallet is paired. This will be set to repeated when multi-account is finished.
       * </pre>
       */
      public boolean getPaired() {
        return paired_;
      }
      /**
       * <code>optional bool paired = 1;</code>
       *
       * <pre>
       * Whether or not the wallet is paired. This will be set to repeated when multi-account is finished.
       * </pre>
       */
      public Builder setPaired(boolean value) {
        bitField0_ |= 0x00000001;
        paired_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool paired = 1;</code>
       *
       * <pre>
       * Whether or not the wallet is paired. This will be set to repeated when multi-account is finished.
       * </pre>
       */
      public Builder clearPaired() {
        bitField0_ = (bitField0_ & ~0x00000001);
        paired_ = false;
        onChanged();
        return this;
      }

      // optional string mpubkey = 2;
      private java.lang.Object mpubkey_ = "";
      /**
       * <code>optional string mpubkey = 2;</code>
       *
       * <pre>
       *Master public key from Authenticator.
       * </pre>
       */
      public boolean hasMpubkey() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string mpubkey = 2;</code>
       *
       * <pre>
       *Master public key from Authenticator.
       * </pre>
       */
      public java.lang.String getMpubkey() {
        java.lang.Object ref = mpubkey_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          mpubkey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string mpubkey = 2;</code>
       *
       * <pre>
       *Master public key from Authenticator.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMpubkeyBytes() {
        java.lang.Object ref = mpubkey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mpubkey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string mpubkey = 2;</code>
       *
       * <pre>
       *Master public key from Authenticator.
       * </pre>
       */
      public Builder setMpubkey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        mpubkey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string mpubkey = 2;</code>
       *
       * <pre>
       *Master public key from Authenticator.
       * </pre>
       */
      public Builder clearMpubkey() {
        bitField0_ = (bitField0_ & ~0x00000002);
        mpubkey_ = getDefaultInstance().getMpubkey();
        onChanged();
        return this;
      }
      /**
       * <code>optional string mpubkey = 2;</code>
       *
       * <pre>
       *Master public key from Authenticator.
       * </pre>
       */
      public Builder setMpubkeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        mpubkey_ = value;
        onChanged();
        return this;
      }

      // optional string chaincode = 3;
      private java.lang.Object chaincode_ = "";
      /**
       * <code>optional string chaincode = 3;</code>
       *
       * <pre>
       *Chaincode from Authenticator.
       * </pre>
       */
      public boolean hasChaincode() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string chaincode = 3;</code>
       *
       * <pre>
       *Chaincode from Authenticator.
       * </pre>
       */
      public java.lang.String getChaincode() {
        java.lang.Object ref = chaincode_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          chaincode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string chaincode = 3;</code>
       *
       * <pre>
       *Chaincode from Authenticator.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getChaincodeBytes() {
        java.lang.Object ref = chaincode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          chaincode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string chaincode = 3;</code>
       *
       * <pre>
       *Chaincode from Authenticator.
       * </pre>
       */
      public Builder setChaincode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        chaincode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string chaincode = 3;</code>
       *
       * <pre>
       *Chaincode from Authenticator.
       * </pre>
       */
      public Builder clearChaincode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        chaincode_ = getDefaultInstance().getChaincode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string chaincode = 3;</code>
       *
       * <pre>
       *Chaincode from Authenticator.
       * </pre>
       */
      public Builder setChaincodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        chaincode_ = value;
        onChanged();
        return this;
      }

      // optional string GMCregID = 4;
      private java.lang.Object gMCregID_ = "";
      /**
       * <code>optional string GMCregID = 4;</code>
       *
       * <pre>
       *GCM ID from Authenticator.
       * </pre>
       */
      public boolean hasGMCregID() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string GMCregID = 4;</code>
       *
       * <pre>
       *GCM ID from Authenticator.
       * </pre>
       */
      public java.lang.String getGMCregID() {
        java.lang.Object ref = gMCregID_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          gMCregID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string GMCregID = 4;</code>
       *
       * <pre>
       *GCM ID from Authenticator.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getGMCregIDBytes() {
        java.lang.Object ref = gMCregID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gMCregID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string GMCregID = 4;</code>
       *
       * <pre>
       *GCM ID from Authenticator.
       * </pre>
       */
      public Builder setGMCregID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        gMCregID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string GMCregID = 4;</code>
       *
       * <pre>
       *GCM ID from Authenticator.
       * </pre>
       */
      public Builder clearGMCregID() {
        bitField0_ = (bitField0_ & ~0x00000008);
        gMCregID_ = getDefaultInstance().getGMCregID();
        onChanged();
        return this;
      }
      /**
       * <code>optional string GMCregID = 4;</code>
       *
       * <pre>
       *GCM ID from Authenticator.
       * </pre>
       */
      public Builder setGMCregIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        gMCregID_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Authenticator)
    }

    static {
      defaultInstance = new Authenticator(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Authenticator)
  }

  public interface ReceiveAddressesOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated string walletKey = 1;
    /**
     * <code>repeated string walletKey = 1;</code>
     *
     * <pre>
     * An array of (min 10) hex encoded public keys from the wallet that will be loaded in the receive pane.
     * </pre>
     */
    java.util.List<java.lang.String>
    getWalletKeyList();
    /**
     * <code>repeated string walletKey = 1;</code>
     *
     * <pre>
     * An array of (min 10) hex encoded public keys from the wallet that will be loaded in the receive pane.
     * </pre>
     */
    int getWalletKeyCount();
    /**
     * <code>repeated string walletKey = 1;</code>
     *
     * <pre>
     * An array of (min 10) hex encoded public keys from the wallet that will be loaded in the receive pane.
     * </pre>
     */
    java.lang.String getWalletKey(int index);
    /**
     * <code>repeated string walletKey = 1;</code>
     *
     * <pre>
     * An array of (min 10) hex encoded public keys from the wallet that will be loaded in the receive pane.
     * </pre>
     */
    com.google.protobuf.ByteString
        getWalletKeyBytes(int index);

    // repeated string authKey = 2;
    /**
     * <code>repeated string authKey = 2;</code>
     *
     * <pre>
     * Same thing but generated from the Authenticator mpubkey. Used when paired.
     * </pre>
     */
    java.util.List<java.lang.String>
    getAuthKeyList();
    /**
     * <code>repeated string authKey = 2;</code>
     *
     * <pre>
     * Same thing but generated from the Authenticator mpubkey. Used when paired.
     * </pre>
     */
    int getAuthKeyCount();
    /**
     * <code>repeated string authKey = 2;</code>
     *
     * <pre>
     * Same thing but generated from the Authenticator mpubkey. Used when paired.
     * </pre>
     */
    java.lang.String getAuthKey(int index);
    /**
     * <code>repeated string authKey = 2;</code>
     *
     * <pre>
     * Same thing but generated from the Authenticator mpubkey. Used when paired.
     * </pre>
     */
    com.google.protobuf.ByteString
        getAuthKeyBytes(int index);
  }
  /**
   * Protobuf type {@code ReceiveAddresses}
   */
  public static final class ReceiveAddresses extends
      com.google.protobuf.GeneratedMessage
      implements ReceiveAddressesOrBuilder {
    // Use ReceiveAddresses.newBuilder() to construct.
    private ReceiveAddresses(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReceiveAddresses(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReceiveAddresses defaultInstance;
    public static ReceiveAddresses getDefaultInstance() {
      return defaultInstance;
    }

    public ReceiveAddresses getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReceiveAddresses(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                walletKey_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              walletKey_.add(input.readBytes());
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                authKey_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              authKey_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          walletKey_ = new com.google.protobuf.UnmodifiableLazyStringList(walletKey_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          authKey_ = new com.google.protobuf.UnmodifiableLazyStringList(authKey_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoConfig.internal_static_ReceiveAddresses_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoConfig.internal_static_ReceiveAddresses_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtoConfig.ReceiveAddresses.class, ProtoConfig.ReceiveAddresses.Builder.class);
    }

    public static com.google.protobuf.Parser<ReceiveAddresses> PARSER =
        new com.google.protobuf.AbstractParser<ReceiveAddresses>() {
      public ReceiveAddresses parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReceiveAddresses(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReceiveAddresses> getParserForType() {
      return PARSER;
    }

    // repeated string walletKey = 1;
    public static final int WALLETKEY_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList walletKey_;
    /**
     * <code>repeated string walletKey = 1;</code>
     *
     * <pre>
     * An array of (min 10) hex encoded public keys from the wallet that will be loaded in the receive pane.
     * </pre>
     */
    public java.util.List<java.lang.String>
        getWalletKeyList() {
      return walletKey_;
    }
    /**
     * <code>repeated string walletKey = 1;</code>
     *
     * <pre>
     * An array of (min 10) hex encoded public keys from the wallet that will be loaded in the receive pane.
     * </pre>
     */
    public int getWalletKeyCount() {
      return walletKey_.size();
    }
    /**
     * <code>repeated string walletKey = 1;</code>
     *
     * <pre>
     * An array of (min 10) hex encoded public keys from the wallet that will be loaded in the receive pane.
     * </pre>
     */
    public java.lang.String getWalletKey(int index) {
      return walletKey_.get(index);
    }
    /**
     * <code>repeated string walletKey = 1;</code>
     *
     * <pre>
     * An array of (min 10) hex encoded public keys from the wallet that will be loaded in the receive pane.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getWalletKeyBytes(int index) {
      return walletKey_.getByteString(index);
    }

    // repeated string authKey = 2;
    public static final int AUTHKEY_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList authKey_;
    /**
     * <code>repeated string authKey = 2;</code>
     *
     * <pre>
     * Same thing but generated from the Authenticator mpubkey. Used when paired.
     * </pre>
     */
    public java.util.List<java.lang.String>
        getAuthKeyList() {
      return authKey_;
    }
    /**
     * <code>repeated string authKey = 2;</code>
     *
     * <pre>
     * Same thing but generated from the Authenticator mpubkey. Used when paired.
     * </pre>
     */
    public int getAuthKeyCount() {
      return authKey_.size();
    }
    /**
     * <code>repeated string authKey = 2;</code>
     *
     * <pre>
     * Same thing but generated from the Authenticator mpubkey. Used when paired.
     * </pre>
     */
    public java.lang.String getAuthKey(int index) {
      return authKey_.get(index);
    }
    /**
     * <code>repeated string authKey = 2;</code>
     *
     * <pre>
     * Same thing but generated from the Authenticator mpubkey. Used when paired.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getAuthKeyBytes(int index) {
      return authKey_.getByteString(index);
    }

    private void initFields() {
      walletKey_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      authKey_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < walletKey_.size(); i++) {
        output.writeBytes(1, walletKey_.getByteString(i));
      }
      for (int i = 0; i < authKey_.size(); i++) {
        output.writeBytes(2, authKey_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < walletKey_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(walletKey_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getWalletKeyList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < authKey_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(authKey_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getAuthKeyList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ProtoConfig.ReceiveAddresses parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoConfig.ReceiveAddresses parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoConfig.ReceiveAddresses parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoConfig.ReceiveAddresses parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoConfig.ReceiveAddresses parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ProtoConfig.ReceiveAddresses parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ProtoConfig.ReceiveAddresses parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ProtoConfig.ReceiveAddresses parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ProtoConfig.ReceiveAddresses parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ProtoConfig.ReceiveAddresses parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ProtoConfig.ReceiveAddresses prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ReceiveAddresses}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ProtoConfig.ReceiveAddressesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoConfig.internal_static_ReceiveAddresses_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoConfig.internal_static_ReceiveAddresses_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoConfig.ReceiveAddresses.class, ProtoConfig.ReceiveAddresses.Builder.class);
      }

      // Construct using ProtoConfig.ReceiveAddresses.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        walletKey_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        authKey_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoConfig.internal_static_ReceiveAddresses_descriptor;
      }

      public ProtoConfig.ReceiveAddresses getDefaultInstanceForType() {
        return ProtoConfig.ReceiveAddresses.getDefaultInstance();
      }

      public ProtoConfig.ReceiveAddresses build() {
        ProtoConfig.ReceiveAddresses result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ProtoConfig.ReceiveAddresses buildPartial() {
        ProtoConfig.ReceiveAddresses result = new ProtoConfig.ReceiveAddresses(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          walletKey_ = new com.google.protobuf.UnmodifiableLazyStringList(
              walletKey_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.walletKey_ = walletKey_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          authKey_ = new com.google.protobuf.UnmodifiableLazyStringList(
              authKey_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.authKey_ = authKey_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoConfig.ReceiveAddresses) {
          return mergeFrom((ProtoConfig.ReceiveAddresses)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtoConfig.ReceiveAddresses other) {
        if (other == ProtoConfig.ReceiveAddresses.getDefaultInstance()) return this;
        if (!other.walletKey_.isEmpty()) {
          if (walletKey_.isEmpty()) {
            walletKey_ = other.walletKey_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureWalletKeyIsMutable();
            walletKey_.addAll(other.walletKey_);
          }
          onChanged();
        }
        if (!other.authKey_.isEmpty()) {
          if (authKey_.isEmpty()) {
            authKey_ = other.authKey_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureAuthKeyIsMutable();
            authKey_.addAll(other.authKey_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtoConfig.ReceiveAddresses parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtoConfig.ReceiveAddresses) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated string walletKey = 1;
      private com.google.protobuf.LazyStringList walletKey_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureWalletKeyIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          walletKey_ = new com.google.protobuf.LazyStringArrayList(walletKey_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string walletKey = 1;</code>
       *
       * <pre>
       * An array of (min 10) hex encoded public keys from the wallet that will be loaded in the receive pane.
       * </pre>
       */
      public java.util.List<java.lang.String>
          getWalletKeyList() {
        return java.util.Collections.unmodifiableList(walletKey_);
      }
      /**
       * <code>repeated string walletKey = 1;</code>
       *
       * <pre>
       * An array of (min 10) hex encoded public keys from the wallet that will be loaded in the receive pane.
       * </pre>
       */
      public int getWalletKeyCount() {
        return walletKey_.size();
      }
      /**
       * <code>repeated string walletKey = 1;</code>
       *
       * <pre>
       * An array of (min 10) hex encoded public keys from the wallet that will be loaded in the receive pane.
       * </pre>
       */
      public java.lang.String getWalletKey(int index) {
        return walletKey_.get(index);
      }
      /**
       * <code>repeated string walletKey = 1;</code>
       *
       * <pre>
       * An array of (min 10) hex encoded public keys from the wallet that will be loaded in the receive pane.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getWalletKeyBytes(int index) {
        return walletKey_.getByteString(index);
      }
      /**
       * <code>repeated string walletKey = 1;</code>
       *
       * <pre>
       * An array of (min 10) hex encoded public keys from the wallet that will be loaded in the receive pane.
       * </pre>
       */
      public Builder setWalletKey(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureWalletKeyIsMutable();
        walletKey_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string walletKey = 1;</code>
       *
       * <pre>
       * An array of (min 10) hex encoded public keys from the wallet that will be loaded in the receive pane.
       * </pre>
       */
      public Builder addWalletKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureWalletKeyIsMutable();
        walletKey_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string walletKey = 1;</code>
       *
       * <pre>
       * An array of (min 10) hex encoded public keys from the wallet that will be loaded in the receive pane.
       * </pre>
       */
      public Builder addAllWalletKey(
          java.lang.Iterable<java.lang.String> values) {
        ensureWalletKeyIsMutable();
        super.addAll(values, walletKey_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string walletKey = 1;</code>
       *
       * <pre>
       * An array of (min 10) hex encoded public keys from the wallet that will be loaded in the receive pane.
       * </pre>
       */
      public Builder clearWalletKey() {
        walletKey_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string walletKey = 1;</code>
       *
       * <pre>
       * An array of (min 10) hex encoded public keys from the wallet that will be loaded in the receive pane.
       * </pre>
       */
      public Builder addWalletKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureWalletKeyIsMutable();
        walletKey_.add(value);
        onChanged();
        return this;
      }

      // repeated string authKey = 2;
      private com.google.protobuf.LazyStringList authKey_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureAuthKeyIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          authKey_ = new com.google.protobuf.LazyStringArrayList(authKey_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string authKey = 2;</code>
       *
       * <pre>
       * Same thing but generated from the Authenticator mpubkey. Used when paired.
       * </pre>
       */
      public java.util.List<java.lang.String>
          getAuthKeyList() {
        return java.util.Collections.unmodifiableList(authKey_);
      }
      /**
       * <code>repeated string authKey = 2;</code>
       *
       * <pre>
       * Same thing but generated from the Authenticator mpubkey. Used when paired.
       * </pre>
       */
      public int getAuthKeyCount() {
        return authKey_.size();
      }
      /**
       * <code>repeated string authKey = 2;</code>
       *
       * <pre>
       * Same thing but generated from the Authenticator mpubkey. Used when paired.
       * </pre>
       */
      public java.lang.String getAuthKey(int index) {
        return authKey_.get(index);
      }
      /**
       * <code>repeated string authKey = 2;</code>
       *
       * <pre>
       * Same thing but generated from the Authenticator mpubkey. Used when paired.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getAuthKeyBytes(int index) {
        return authKey_.getByteString(index);
      }
      /**
       * <code>repeated string authKey = 2;</code>
       *
       * <pre>
       * Same thing but generated from the Authenticator mpubkey. Used when paired.
       * </pre>
       */
      public Builder setAuthKey(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAuthKeyIsMutable();
        authKey_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string authKey = 2;</code>
       *
       * <pre>
       * Same thing but generated from the Authenticator mpubkey. Used when paired.
       * </pre>
       */
      public Builder addAuthKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAuthKeyIsMutable();
        authKey_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string authKey = 2;</code>
       *
       * <pre>
       * Same thing but generated from the Authenticator mpubkey. Used when paired.
       * </pre>
       */
      public Builder addAllAuthKey(
          java.lang.Iterable<java.lang.String> values) {
        ensureAuthKeyIsMutable();
        super.addAll(values, authKey_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string authKey = 2;</code>
       *
       * <pre>
       * Same thing but generated from the Authenticator mpubkey. Used when paired.
       * </pre>
       */
      public Builder clearAuthKey() {
        authKey_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string authKey = 2;</code>
       *
       * <pre>
       * Same thing but generated from the Authenticator mpubkey. Used when paired.
       * </pre>
       */
      public Builder addAuthKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAuthKeyIsMutable();
        authKey_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ReceiveAddresses)
    }

    static {
      defaultInstance = new ReceiveAddresses(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ReceiveAddresses)
  }

  public interface AddressBookOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string address = 1;
    /**
     * <code>optional string address = 1;</code>
     *
     * <pre>
     * This is a placeholder for the address book.
     * </pre>
     */
    boolean hasAddress();
    /**
     * <code>optional string address = 1;</code>
     *
     * <pre>
     * This is a placeholder for the address book.
     * </pre>
     */
    java.lang.String getAddress();
    /**
     * <code>optional string address = 1;</code>
     *
     * <pre>
     * This is a placeholder for the address book.
     * </pre>
     */
    com.google.protobuf.ByteString
        getAddressBytes();
  }
  /**
   * Protobuf type {@code AddressBook}
   */
  public static final class AddressBook extends
      com.google.protobuf.GeneratedMessage
      implements AddressBookOrBuilder {
    // Use AddressBook.newBuilder() to construct.
    private AddressBook(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AddressBook(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AddressBook defaultInstance;
    public static AddressBook getDefaultInstance() {
      return defaultInstance;
    }

    public AddressBook getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AddressBook(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              address_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoConfig.internal_static_AddressBook_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoConfig.internal_static_AddressBook_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtoConfig.AddressBook.class, ProtoConfig.AddressBook.Builder.class);
    }

    public static com.google.protobuf.Parser<AddressBook> PARSER =
        new com.google.protobuf.AbstractParser<AddressBook>() {
      public AddressBook parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AddressBook(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AddressBook> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string address = 1;
    public static final int ADDRESS_FIELD_NUMBER = 1;
    private java.lang.Object address_;
    /**
     * <code>optional string address = 1;</code>
     *
     * <pre>
     * This is a placeholder for the address book.
     * </pre>
     */
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string address = 1;</code>
     *
     * <pre>
     * This is a placeholder for the address book.
     * </pre>
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          address_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string address = 1;</code>
     *
     * <pre>
     * This is a placeholder for the address book.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      address_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getAddressBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getAddressBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ProtoConfig.AddressBook parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoConfig.AddressBook parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoConfig.AddressBook parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoConfig.AddressBook parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoConfig.AddressBook parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ProtoConfig.AddressBook parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ProtoConfig.AddressBook parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ProtoConfig.AddressBook parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ProtoConfig.AddressBook parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ProtoConfig.AddressBook parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ProtoConfig.AddressBook prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AddressBook}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ProtoConfig.AddressBookOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoConfig.internal_static_AddressBook_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoConfig.internal_static_AddressBook_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoConfig.AddressBook.class, ProtoConfig.AddressBook.Builder.class);
      }

      // Construct using ProtoConfig.AddressBook.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        address_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoConfig.internal_static_AddressBook_descriptor;
      }

      public ProtoConfig.AddressBook getDefaultInstanceForType() {
        return ProtoConfig.AddressBook.getDefaultInstance();
      }

      public ProtoConfig.AddressBook build() {
        ProtoConfig.AddressBook result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ProtoConfig.AddressBook buildPartial() {
        ProtoConfig.AddressBook result = new ProtoConfig.AddressBook(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.address_ = address_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoConfig.AddressBook) {
          return mergeFrom((ProtoConfig.AddressBook)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtoConfig.AddressBook other) {
        if (other == ProtoConfig.AddressBook.getDefaultInstance()) return this;
        if (other.hasAddress()) {
          bitField0_ |= 0x00000001;
          address_ = other.address_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtoConfig.AddressBook parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtoConfig.AddressBook) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string address = 1;
      private java.lang.Object address_ = "";
      /**
       * <code>optional string address = 1;</code>
       *
       * <pre>
       * This is a placeholder for the address book.
       * </pre>
       */
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string address = 1;</code>
       *
       * <pre>
       * This is a placeholder for the address book.
       * </pre>
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string address = 1;</code>
       *
       * <pre>
       * This is a placeholder for the address book.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string address = 1;</code>
       *
       * <pre>
       * This is a placeholder for the address book.
       * </pre>
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string address = 1;</code>
       *
       * <pre>
       * This is a placeholder for the address book.
       * </pre>
       */
      public Builder clearAddress() {
        bitField0_ = (bitField0_ & ~0x00000001);
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>optional string address = 1;</code>
       *
       * <pre>
       * This is a placeholder for the address book.
       * </pre>
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        address_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:AddressBook)
    }

    static {
      defaultInstance = new AddressBook(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:AddressBook)
  }

  public interface SettingsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string onename = 1;
    /**
     * <code>optional string onename = 1;</code>
     *
     * <pre>
     * The user's OneName ID. Used for getting the avatar on start up.
     * </pre>
     */
    boolean hasOnename();
    /**
     * <code>optional string onename = 1;</code>
     *
     * <pre>
     * The user's OneName ID. Used for getting the avatar on start up.
     * </pre>
     */
    java.lang.String getOnename();
    /**
     * <code>optional string onename = 1;</code>
     *
     * <pre>
     * The user's OneName ID. Used for getting the avatar on start up.
     * </pre>
     */
    com.google.protobuf.ByteString
        getOnenameBytes();
  }
  /**
   * Protobuf type {@code Settings}
   */
  public static final class Settings extends
      com.google.protobuf.GeneratedMessage
      implements SettingsOrBuilder {
    // Use Settings.newBuilder() to construct.
    private Settings(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Settings(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Settings defaultInstance;
    public static Settings getDefaultInstance() {
      return defaultInstance;
    }

    public Settings getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Settings(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              onename_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoConfig.internal_static_Settings_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoConfig.internal_static_Settings_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtoConfig.Settings.class, ProtoConfig.Settings.Builder.class);
    }

    public static com.google.protobuf.Parser<Settings> PARSER =
        new com.google.protobuf.AbstractParser<Settings>() {
      public Settings parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Settings(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Settings> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string onename = 1;
    public static final int ONENAME_FIELD_NUMBER = 1;
    private java.lang.Object onename_;
    /**
     * <code>optional string onename = 1;</code>
     *
     * <pre>
     * The user's OneName ID. Used for getting the avatar on start up.
     * </pre>
     */
    public boolean hasOnename() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string onename = 1;</code>
     *
     * <pre>
     * The user's OneName ID. Used for getting the avatar on start up.
     * </pre>
     */
    public java.lang.String getOnename() {
      java.lang.Object ref = onename_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          onename_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string onename = 1;</code>
     *
     * <pre>
     * The user's OneName ID. Used for getting the avatar on start up.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getOnenameBytes() {
      java.lang.Object ref = onename_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        onename_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      onename_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getOnenameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getOnenameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ProtoConfig.Settings parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoConfig.Settings parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoConfig.Settings parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoConfig.Settings parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoConfig.Settings parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ProtoConfig.Settings parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ProtoConfig.Settings parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ProtoConfig.Settings parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ProtoConfig.Settings parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ProtoConfig.Settings parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ProtoConfig.Settings prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Settings}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ProtoConfig.SettingsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoConfig.internal_static_Settings_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoConfig.internal_static_Settings_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoConfig.Settings.class, ProtoConfig.Settings.Builder.class);
      }

      // Construct using ProtoConfig.Settings.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        onename_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoConfig.internal_static_Settings_descriptor;
      }

      public ProtoConfig.Settings getDefaultInstanceForType() {
        return ProtoConfig.Settings.getDefaultInstance();
      }

      public ProtoConfig.Settings build() {
        ProtoConfig.Settings result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ProtoConfig.Settings buildPartial() {
        ProtoConfig.Settings result = new ProtoConfig.Settings(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.onename_ = onename_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoConfig.Settings) {
          return mergeFrom((ProtoConfig.Settings)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtoConfig.Settings other) {
        if (other == ProtoConfig.Settings.getDefaultInstance()) return this;
        if (other.hasOnename()) {
          bitField0_ |= 0x00000001;
          onename_ = other.onename_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtoConfig.Settings parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtoConfig.Settings) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string onename = 1;
      private java.lang.Object onename_ = "";
      /**
       * <code>optional string onename = 1;</code>
       *
       * <pre>
       * The user's OneName ID. Used for getting the avatar on start up.
       * </pre>
       */
      public boolean hasOnename() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string onename = 1;</code>
       *
       * <pre>
       * The user's OneName ID. Used for getting the avatar on start up.
       * </pre>
       */
      public java.lang.String getOnename() {
        java.lang.Object ref = onename_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          onename_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string onename = 1;</code>
       *
       * <pre>
       * The user's OneName ID. Used for getting the avatar on start up.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getOnenameBytes() {
        java.lang.Object ref = onename_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          onename_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string onename = 1;</code>
       *
       * <pre>
       * The user's OneName ID. Used for getting the avatar on start up.
       * </pre>
       */
      public Builder setOnename(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        onename_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string onename = 1;</code>
       *
       * <pre>
       * The user's OneName ID. Used for getting the avatar on start up.
       * </pre>
       */
      public Builder clearOnename() {
        bitField0_ = (bitField0_ & ~0x00000001);
        onename_ = getDefaultInstance().getOnename();
        onChanged();
        return this;
      }
      /**
       * <code>optional string onename = 1;</code>
       *
       * <pre>
       * The user's OneName ID. Used for getting the avatar on start up.
       * </pre>
       */
      public Builder setOnenameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        onename_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Settings)
    }

    static {
      defaultInstance = new Settings(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Settings)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Authenticator_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Authenticator_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ReceiveAddresses_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ReceiveAddresses_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_AddressBook_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AddressBook_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Settings_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Settings_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014config.proto\"U\n\rAuthenticator\022\016\n\006paire" +
      "d\030\001 \001(\010\022\017\n\007mpubkey\030\002 \001(\t\022\021\n\tchaincode\030\003 " +
      "\001(\t\022\020\n\010GMCregID\030\004 \001(\t\"6\n\020ReceiveAddresse" +
      "s\022\021\n\twalletKey\030\001 \003(\t\022\017\n\007authKey\030\002 \003(\t\"\036\n" +
      "\013AddressBook\022\017\n\007address\030\001 \001(\t\"\033\n\010Setting" +
      "s\022\017\n\007onename\030\001 \001(\tB\rB\013ProtoConfig"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Authenticator_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Authenticator_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Authenticator_descriptor,
              new java.lang.String[] { "Paired", "Mpubkey", "Chaincode", "GMCregID", });
          internal_static_ReceiveAddresses_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_ReceiveAddresses_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ReceiveAddresses_descriptor,
              new java.lang.String[] { "WalletKey", "AuthKey", });
          internal_static_AddressBook_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_AddressBook_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_AddressBook_descriptor,
              new java.lang.String[] { "Address", });
          internal_static_Settings_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_Settings_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Settings_descriptor,
              new java.lang.String[] { "Onename", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
