// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BAHierarchy.proto

package org.authenticator.protobuf;

public final class AuthWalletHierarchy {
  private AuthWalletHierarchy() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code org.authenticator.protobuf.HierarchyPurpose}
   */
  public enum HierarchyPurpose
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Bip43 = 44;</code>
     *
     * <pre>
     * 0x8000002C as in Bip43
     * </pre>
     */
    Bip43(0, 44),
    /**
     * <code>BAGeneral = 100;</code>
     *
     * <pre>
     * 0x8000006E
     * </pre>
     */
    BAGeneral(1, 100),
    ;

    /**
     * <code>Bip43 = 44;</code>
     *
     * <pre>
     * 0x8000002C as in Bip43
     * </pre>
     */
    public static final int Bip43_VALUE = 44;
    /**
     * <code>BAGeneral = 100;</code>
     *
     * <pre>
     * 0x8000006E
     * </pre>
     */
    public static final int BAGeneral_VALUE = 100;


    public final int getNumber() { return value; }

    public static HierarchyPurpose valueOf(int value) {
      switch (value) {
        case 44: return Bip43;
        case 100: return BAGeneral;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<HierarchyPurpose>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<HierarchyPurpose>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<HierarchyPurpose>() {
            public HierarchyPurpose findValueByNumber(int number) {
              return HierarchyPurpose.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.authenticator.protobuf.AuthWalletHierarchy.getDescriptor().getEnumTypes().get(0);
    }

    private static final HierarchyPurpose[] VALUES = values();

    public static HierarchyPurpose valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private HierarchyPurpose(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:org.authenticator.protobuf.HierarchyPurpose)
  }

  /**
   * Protobuf enum {@code org.authenticator.protobuf.HierarchyCoinTypes}
   */
  public enum HierarchyCoinTypes
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CoinBitcoin = 0;</code>
     *
     * <pre>
     * 0x80000000 as in Bip44
     * </pre>
     */
    CoinBitcoin(0, 0),
    ;

    /**
     * <code>CoinBitcoin = 0;</code>
     *
     * <pre>
     * 0x80000000 as in Bip44
     * </pre>
     */
    public static final int CoinBitcoin_VALUE = 0;


    public final int getNumber() { return value; }

    public static HierarchyCoinTypes valueOf(int value) {
      switch (value) {
        case 0: return CoinBitcoin;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<HierarchyCoinTypes>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<HierarchyCoinTypes>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<HierarchyCoinTypes>() {
            public HierarchyCoinTypes findValueByNumber(int number) {
              return HierarchyCoinTypes.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.authenticator.protobuf.AuthWalletHierarchy.getDescriptor().getEnumTypes().get(1);
    }

    private static final HierarchyCoinTypes[] VALUES = values();

    public static HierarchyCoinTypes valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private HierarchyCoinTypes(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:org.authenticator.protobuf.HierarchyCoinTypes)
  }

  /**
   * Protobuf enum {@code org.authenticator.protobuf.HierarchyAddressTypes}
   */
  public enum HierarchyAddressTypes
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>External = 0;</code>
     *
     * <pre>
     * external
     * </pre>
     */
    External(0, 0),
    /**
     * <code>Internal = 1;</code>
     *
     * <pre>
     * internal / change
     * </pre>
     */
    Internal(1, 1),
    ;

    /**
     * <code>External = 0;</code>
     *
     * <pre>
     * external
     * </pre>
     */
    public static final int External_VALUE = 0;
    /**
     * <code>Internal = 1;</code>
     *
     * <pre>
     * internal / change
     * </pre>
     */
    public static final int Internal_VALUE = 1;


    public final int getNumber() { return value; }

    public static HierarchyAddressTypes valueOf(int value) {
      switch (value) {
        case 0: return External;
        case 1: return Internal;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<HierarchyAddressTypes>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<HierarchyAddressTypes>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<HierarchyAddressTypes>() {
            public HierarchyAddressTypes findValueByNumber(int number) {
              return HierarchyAddressTypes.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.authenticator.protobuf.AuthWalletHierarchy.getDescriptor().getEnumTypes().get(2);
    }

    private static final HierarchyAddressTypes[] VALUES = values();

    public static HierarchyAddressTypes valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private HierarchyAddressTypes(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:org.authenticator.protobuf.HierarchyAddressTypes)
  }

  /**
   * Protobuf enum {@code org.authenticator.protobuf.BAGeneralHierarchyKeys}
   */
  public enum BAGeneralHierarchyKeys
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ConfigFileEncryption = 0;</code>
     */
    ConfigFileEncryption(0, 0),
    /**
     * <code>CloudBackupEncryption = 1;</code>
     */
    CloudBackupEncryption(1, 1),
    ;

    /**
     * <code>ConfigFileEncryption = 0;</code>
     */
    public static final int ConfigFileEncryption_VALUE = 0;
    /**
     * <code>CloudBackupEncryption = 1;</code>
     */
    public static final int CloudBackupEncryption_VALUE = 1;


    public final int getNumber() { return value; }

    public static BAGeneralHierarchyKeys valueOf(int value) {
      switch (value) {
        case 0: return ConfigFileEncryption;
        case 1: return CloudBackupEncryption;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<BAGeneralHierarchyKeys>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<BAGeneralHierarchyKeys>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<BAGeneralHierarchyKeys>() {
            public BAGeneralHierarchyKeys findValueByNumber(int number) {
              return BAGeneralHierarchyKeys.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.authenticator.protobuf.AuthWalletHierarchy.getDescriptor().getEnumTypes().get(3);
    }

    private static final BAGeneralHierarchyKeys[] VALUES = values();

    public static BAGeneralHierarchyKeys valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private BAGeneralHierarchyKeys(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:org.authenticator.protobuf.BAGeneralHierarchyKeys)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021BAHierarchy.proto\022\032org.authenticator.p" +
      "rotobuf*,\n\020HierarchyPurpose\022\t\n\005Bip43\020,\022\r" +
      "\n\tBAGeneral\020d*%\n\022HierarchyCoinTypes\022\017\n\013C" +
      "oinBitcoin\020\000*3\n\025HierarchyAddressTypes\022\014\n" +
      "\010External\020\000\022\014\n\010Internal\020\001*M\n\026BAGeneralHi" +
      "erarchyKeys\022\030\n\024ConfigFileEncryption\020\000\022\031\n" +
      "\025CloudBackupEncryption\020\001B\025B\023AuthWalletHi" +
      "erarchy"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
