// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: configSettings.proto

package org.authenticator.protobuf;

public final class ProtoSettings {
  private ProtoSettings() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(org.authenticator.protobuf.ProtoSettings.bitcoinUnitName);
  }
  /**
   * Protobuf enum {@code org.authenticator.protobuf.BitcoinUnit}
   */
  public enum BitcoinUnit
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>BTC = 0;</code>
     */
    BTC(0, 0),
    /**
     * <code>Millibits = 1;</code>
     */
    Millibits(1, 1),
    /**
     * <code>Microbits = 2;</code>
     */
    Microbits(2, 2),
    ;

    /**
     * <code>BTC = 0;</code>
     */
    public static final int BTC_VALUE = 0;
    /**
     * <code>Millibits = 1;</code>
     */
    public static final int Millibits_VALUE = 1;
    /**
     * <code>Microbits = 2;</code>
     */
    public static final int Microbits_VALUE = 2;


    public final int getNumber() { return value; }

    public static BitcoinUnit valueOf(int value) {
      switch (value) {
        case 0: return BTC;
        case 1: return Millibits;
        case 2: return Microbits;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<BitcoinUnit>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<BitcoinUnit>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<BitcoinUnit>() {
            public BitcoinUnit findValueByNumber(int number) {
              return BitcoinUnit.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.authenticator.protobuf.ProtoSettings.getDescriptor().getEnumTypes().get(0);
    }

    private static final BitcoinUnit[] VALUES = values();

    public static BitcoinUnit valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private BitcoinUnit(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:org.authenticator.protobuf.BitcoinUnit)
  }

  /**
   * Protobuf enum {@code org.authenticator.protobuf.Languages}
   */
  public enum Languages
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>English = 0;</code>
     */
    English(0, 0),
    ;

    /**
     * <code>English = 0;</code>
     */
    public static final int English_VALUE = 0;


    public final int getNumber() { return value; }

    public static Languages valueOf(int value) {
      switch (value) {
        case 0: return English;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Languages>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Languages>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Languages>() {
            public Languages findValueByNumber(int number) {
              return Languages.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.authenticator.protobuf.ProtoSettings.getDescriptor().getEnumTypes().get(1);
    }

    private static final Languages[] VALUES = values();

    public static Languages valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Languages(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:org.authenticator.protobuf.Languages)
  }

  public interface ConfigSettingsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.authenticator.protobuf.ConfigSettings)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .org.authenticator.protobuf.BitcoinUnit accountUnit = 1 [default = BTC];</code>
     */
    boolean hasAccountUnit();
    /**
     * <code>optional .org.authenticator.protobuf.BitcoinUnit accountUnit = 1 [default = BTC];</code>
     */
    org.authenticator.protobuf.ProtoSettings.BitcoinUnit getAccountUnit();

    /**
     * <code>optional int32 decimalPoints = 2 [default = 4];</code>
     */
    boolean hasDecimalPoints();
    /**
     * <code>optional int32 decimalPoints = 2 [default = 4];</code>
     */
    int getDecimalPoints();

    /**
     * <code>optional string localCurrencySymbol = 3 [default = "USD"];</code>
     */
    boolean hasLocalCurrencySymbol();
    /**
     * <code>optional string localCurrencySymbol = 3 [default = "USD"];</code>
     */
    java.lang.String getLocalCurrencySymbol();
    /**
     * <code>optional string localCurrencySymbol = 3 [default = "USD"];</code>
     */
    com.google.protobuf.ByteString
        getLocalCurrencySymbolBytes();

    /**
     * <code>optional .org.authenticator.protobuf.Languages language = 4 [default = English];</code>
     */
    boolean hasLanguage();
    /**
     * <code>optional .org.authenticator.protobuf.Languages language = 4 [default = English];</code>
     */
    org.authenticator.protobuf.ProtoSettings.Languages getLanguage();

    /**
     * <code>optional int32 defaultFee = 5 [default = 10000];</code>
     *
     * <pre>
     * in satoshies
     * </pre>
     */
    boolean hasDefaultFee();
    /**
     * <code>optional int32 defaultFee = 5 [default = 10000];</code>
     *
     * <pre>
     * in satoshies
     * </pre>
     */
    int getDefaultFee();

    /**
     * <code>optional bool TOR = 6 [default = true];</code>
     *
     * <pre>
     * flags
     * </pre>
     */
    boolean hasTOR();
    /**
     * <code>optional bool TOR = 6 [default = true];</code>
     *
     * <pre>
     * flags
     * </pre>
     */
    boolean getTOR();

    /**
     * <code>optional bool connectOnLocalHost = 7 [default = false];</code>
     */
    boolean hasConnectOnLocalHost();
    /**
     * <code>optional bool connectOnLocalHost = 7 [default = false];</code>
     */
    boolean getConnectOnLocalHost();

    /**
     * <code>optional bool connectToTrustedPeer = 8 [default = false];</code>
     */
    boolean hasConnectToTrustedPeer();
    /**
     * <code>optional bool connectToTrustedPeer = 8 [default = false];</code>
     */
    boolean getConnectToTrustedPeer();

    /**
     * <code>optional bool portForwarding = 9 [default = false];</code>
     */
    boolean hasPortForwarding();
    /**
     * <code>optional bool portForwarding = 9 [default = false];</code>
     */
    boolean getPortForwarding();

    /**
     * <code>optional string trustedPeerIP = 10;</code>
     */
    boolean hasTrustedPeerIP();
    /**
     * <code>optional string trustedPeerIP = 10;</code>
     */
    java.lang.String getTrustedPeerIP();
    /**
     * <code>optional string trustedPeerIP = 10;</code>
     */
    com.google.protobuf.ByteString
        getTrustedPeerIPBytes();

    /**
     * <code>optional float bloomFilterFalsePositiveRate = 11 [default = 1e-05];</code>
     */
    boolean hasBloomFilterFalsePositiveRate();
    /**
     * <code>optional float bloomFilterFalsePositiveRate = 11 [default = 1e-05];</code>
     */
    float getBloomFilterFalsePositiveRate();
  }
  /**
   * Protobuf type {@code org.authenticator.protobuf.ConfigSettings}
   */
  public static final class ConfigSettings extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.authenticator.protobuf.ConfigSettings)
      ConfigSettingsOrBuilder {
    // Use ConfigSettings.newBuilder() to construct.
    private ConfigSettings(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ConfigSettings(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ConfigSettings defaultInstance;
    public static ConfigSettings getDefaultInstance() {
      return defaultInstance;
    }

    public ConfigSettings getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ConfigSettings(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              org.authenticator.protobuf.ProtoSettings.BitcoinUnit value = org.authenticator.protobuf.ProtoSettings.BitcoinUnit.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                accountUnit_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              decimalPoints_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              localCurrencySymbol_ = bs;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              org.authenticator.protobuf.ProtoSettings.Languages value = org.authenticator.protobuf.ProtoSettings.Languages.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                language_ = value;
              }
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              defaultFee_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              tOR_ = input.readBool();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              connectOnLocalHost_ = input.readBool();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              connectToTrustedPeer_ = input.readBool();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              portForwarding_ = input.readBool();
              break;
            }
            case 82: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000200;
              trustedPeerIP_ = bs;
              break;
            }
            case 93: {
              bitField0_ |= 0x00000400;
              bloomFilterFalsePositiveRate_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.authenticator.protobuf.ProtoSettings.internal_static_org_authenticator_protobuf_ConfigSettings_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.authenticator.protobuf.ProtoSettings.internal_static_org_authenticator_protobuf_ConfigSettings_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.authenticator.protobuf.ProtoSettings.ConfigSettings.class, org.authenticator.protobuf.ProtoSettings.ConfigSettings.Builder.class);
    }

    public static com.google.protobuf.Parser<ConfigSettings> PARSER =
        new com.google.protobuf.AbstractParser<ConfigSettings>() {
      public ConfigSettings parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConfigSettings(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ConfigSettings> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ACCOUNTUNIT_FIELD_NUMBER = 1;
    private org.authenticator.protobuf.ProtoSettings.BitcoinUnit accountUnit_;
    /**
     * <code>optional .org.authenticator.protobuf.BitcoinUnit accountUnit = 1 [default = BTC];</code>
     */
    public boolean hasAccountUnit() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .org.authenticator.protobuf.BitcoinUnit accountUnit = 1 [default = BTC];</code>
     */
    public org.authenticator.protobuf.ProtoSettings.BitcoinUnit getAccountUnit() {
      return accountUnit_;
    }

    public static final int DECIMALPOINTS_FIELD_NUMBER = 2;
    private int decimalPoints_;
    /**
     * <code>optional int32 decimalPoints = 2 [default = 4];</code>
     */
    public boolean hasDecimalPoints() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 decimalPoints = 2 [default = 4];</code>
     */
    public int getDecimalPoints() {
      return decimalPoints_;
    }

    public static final int LOCALCURRENCYSYMBOL_FIELD_NUMBER = 3;
    private java.lang.Object localCurrencySymbol_;
    /**
     * <code>optional string localCurrencySymbol = 3 [default = "USD"];</code>
     */
    public boolean hasLocalCurrencySymbol() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string localCurrencySymbol = 3 [default = "USD"];</code>
     */
    public java.lang.String getLocalCurrencySymbol() {
      java.lang.Object ref = localCurrencySymbol_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          localCurrencySymbol_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string localCurrencySymbol = 3 [default = "USD"];</code>
     */
    public com.google.protobuf.ByteString
        getLocalCurrencySymbolBytes() {
      java.lang.Object ref = localCurrencySymbol_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        localCurrencySymbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LANGUAGE_FIELD_NUMBER = 4;
    private org.authenticator.protobuf.ProtoSettings.Languages language_;
    /**
     * <code>optional .org.authenticator.protobuf.Languages language = 4 [default = English];</code>
     */
    public boolean hasLanguage() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .org.authenticator.protobuf.Languages language = 4 [default = English];</code>
     */
    public org.authenticator.protobuf.ProtoSettings.Languages getLanguage() {
      return language_;
    }

    public static final int DEFAULTFEE_FIELD_NUMBER = 5;
    private int defaultFee_;
    /**
     * <code>optional int32 defaultFee = 5 [default = 10000];</code>
     *
     * <pre>
     * in satoshies
     * </pre>
     */
    public boolean hasDefaultFee() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 defaultFee = 5 [default = 10000];</code>
     *
     * <pre>
     * in satoshies
     * </pre>
     */
    public int getDefaultFee() {
      return defaultFee_;
    }

    public static final int TOR_FIELD_NUMBER = 6;
    private boolean tOR_;
    /**
     * <code>optional bool TOR = 6 [default = true];</code>
     *
     * <pre>
     * flags
     * </pre>
     */
    public boolean hasTOR() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional bool TOR = 6 [default = true];</code>
     *
     * <pre>
     * flags
     * </pre>
     */
    public boolean getTOR() {
      return tOR_;
    }

    public static final int CONNECTONLOCALHOST_FIELD_NUMBER = 7;
    private boolean connectOnLocalHost_;
    /**
     * <code>optional bool connectOnLocalHost = 7 [default = false];</code>
     */
    public boolean hasConnectOnLocalHost() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional bool connectOnLocalHost = 7 [default = false];</code>
     */
    public boolean getConnectOnLocalHost() {
      return connectOnLocalHost_;
    }

    public static final int CONNECTTOTRUSTEDPEER_FIELD_NUMBER = 8;
    private boolean connectToTrustedPeer_;
    /**
     * <code>optional bool connectToTrustedPeer = 8 [default = false];</code>
     */
    public boolean hasConnectToTrustedPeer() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional bool connectToTrustedPeer = 8 [default = false];</code>
     */
    public boolean getConnectToTrustedPeer() {
      return connectToTrustedPeer_;
    }

    public static final int PORTFORWARDING_FIELD_NUMBER = 9;
    private boolean portForwarding_;
    /**
     * <code>optional bool portForwarding = 9 [default = false];</code>
     */
    public boolean hasPortForwarding() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional bool portForwarding = 9 [default = false];</code>
     */
    public boolean getPortForwarding() {
      return portForwarding_;
    }

    public static final int TRUSTEDPEERIP_FIELD_NUMBER = 10;
    private java.lang.Object trustedPeerIP_;
    /**
     * <code>optional string trustedPeerIP = 10;</code>
     */
    public boolean hasTrustedPeerIP() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional string trustedPeerIP = 10;</code>
     */
    public java.lang.String getTrustedPeerIP() {
      java.lang.Object ref = trustedPeerIP_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          trustedPeerIP_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string trustedPeerIP = 10;</code>
     */
    public com.google.protobuf.ByteString
        getTrustedPeerIPBytes() {
      java.lang.Object ref = trustedPeerIP_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        trustedPeerIP_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BLOOMFILTERFALSEPOSITIVERATE_FIELD_NUMBER = 11;
    private float bloomFilterFalsePositiveRate_;
    /**
     * <code>optional float bloomFilterFalsePositiveRate = 11 [default = 1e-05];</code>
     */
    public boolean hasBloomFilterFalsePositiveRate() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional float bloomFilterFalsePositiveRate = 11 [default = 1e-05];</code>
     */
    public float getBloomFilterFalsePositiveRate() {
      return bloomFilterFalsePositiveRate_;
    }

    private void initFields() {
      accountUnit_ = org.authenticator.protobuf.ProtoSettings.BitcoinUnit.BTC;
      decimalPoints_ = 4;
      localCurrencySymbol_ = "USD";
      language_ = org.authenticator.protobuf.ProtoSettings.Languages.English;
      defaultFee_ = 10000;
      tOR_ = true;
      connectOnLocalHost_ = false;
      connectToTrustedPeer_ = false;
      portForwarding_ = false;
      trustedPeerIP_ = "";
      bloomFilterFalsePositiveRate_ = 1e-05F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, accountUnit_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, decimalPoints_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getLocalCurrencySymbolBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, language_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, defaultFee_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBool(6, tOR_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBool(7, connectOnLocalHost_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBool(8, connectToTrustedPeer_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBool(9, portForwarding_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, getTrustedPeerIPBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeFloat(11, bloomFilterFalsePositiveRate_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, accountUnit_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, decimalPoints_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getLocalCurrencySymbolBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, language_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, defaultFee_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, tOR_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, connectOnLocalHost_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, connectToTrustedPeer_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(9, portForwarding_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getTrustedPeerIPBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(11, bloomFilterFalsePositiveRate_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.authenticator.protobuf.ProtoSettings.ConfigSettings parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.authenticator.protobuf.ProtoSettings.ConfigSettings parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.authenticator.protobuf.ProtoSettings.ConfigSettings parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.authenticator.protobuf.ProtoSettings.ConfigSettings parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.authenticator.protobuf.ProtoSettings.ConfigSettings parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.authenticator.protobuf.ProtoSettings.ConfigSettings parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.authenticator.protobuf.ProtoSettings.ConfigSettings parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.authenticator.protobuf.ProtoSettings.ConfigSettings parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.authenticator.protobuf.ProtoSettings.ConfigSettings parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.authenticator.protobuf.ProtoSettings.ConfigSettings parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.authenticator.protobuf.ProtoSettings.ConfigSettings prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.authenticator.protobuf.ConfigSettings}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.authenticator.protobuf.ConfigSettings)
        org.authenticator.protobuf.ProtoSettings.ConfigSettingsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.authenticator.protobuf.ProtoSettings.internal_static_org_authenticator_protobuf_ConfigSettings_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.authenticator.protobuf.ProtoSettings.internal_static_org_authenticator_protobuf_ConfigSettings_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.authenticator.protobuf.ProtoSettings.ConfigSettings.class, org.authenticator.protobuf.ProtoSettings.ConfigSettings.Builder.class);
      }

      // Construct using org.authenticator.protobuf.ProtoSettings.ConfigSettings.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        accountUnit_ = org.authenticator.protobuf.ProtoSettings.BitcoinUnit.BTC;
        bitField0_ = (bitField0_ & ~0x00000001);
        decimalPoints_ = 4;
        bitField0_ = (bitField0_ & ~0x00000002);
        localCurrencySymbol_ = "USD";
        bitField0_ = (bitField0_ & ~0x00000004);
        language_ = org.authenticator.protobuf.ProtoSettings.Languages.English;
        bitField0_ = (bitField0_ & ~0x00000008);
        defaultFee_ = 10000;
        bitField0_ = (bitField0_ & ~0x00000010);
        tOR_ = true;
        bitField0_ = (bitField0_ & ~0x00000020);
        connectOnLocalHost_ = false;
        bitField0_ = (bitField0_ & ~0x00000040);
        connectToTrustedPeer_ = false;
        bitField0_ = (bitField0_ & ~0x00000080);
        portForwarding_ = false;
        bitField0_ = (bitField0_ & ~0x00000100);
        trustedPeerIP_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        bloomFilterFalsePositiveRate_ = 1e-05F;
        bitField0_ = (bitField0_ & ~0x00000400);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.authenticator.protobuf.ProtoSettings.internal_static_org_authenticator_protobuf_ConfigSettings_descriptor;
      }

      public org.authenticator.protobuf.ProtoSettings.ConfigSettings getDefaultInstanceForType() {
        return org.authenticator.protobuf.ProtoSettings.ConfigSettings.getDefaultInstance();
      }

      public org.authenticator.protobuf.ProtoSettings.ConfigSettings build() {
        org.authenticator.protobuf.ProtoSettings.ConfigSettings result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.authenticator.protobuf.ProtoSettings.ConfigSettings buildPartial() {
        org.authenticator.protobuf.ProtoSettings.ConfigSettings result = new org.authenticator.protobuf.ProtoSettings.ConfigSettings(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.accountUnit_ = accountUnit_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.decimalPoints_ = decimalPoints_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.localCurrencySymbol_ = localCurrencySymbol_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.language_ = language_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.defaultFee_ = defaultFee_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.tOR_ = tOR_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.connectOnLocalHost_ = connectOnLocalHost_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.connectToTrustedPeer_ = connectToTrustedPeer_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.portForwarding_ = portForwarding_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.trustedPeerIP_ = trustedPeerIP_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.bloomFilterFalsePositiveRate_ = bloomFilterFalsePositiveRate_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.authenticator.protobuf.ProtoSettings.ConfigSettings) {
          return mergeFrom((org.authenticator.protobuf.ProtoSettings.ConfigSettings)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.authenticator.protobuf.ProtoSettings.ConfigSettings other) {
        if (other == org.authenticator.protobuf.ProtoSettings.ConfigSettings.getDefaultInstance()) return this;
        if (other.hasAccountUnit()) {
          setAccountUnit(other.getAccountUnit());
        }
        if (other.hasDecimalPoints()) {
          setDecimalPoints(other.getDecimalPoints());
        }
        if (other.hasLocalCurrencySymbol()) {
          bitField0_ |= 0x00000004;
          localCurrencySymbol_ = other.localCurrencySymbol_;
          onChanged();
        }
        if (other.hasLanguage()) {
          setLanguage(other.getLanguage());
        }
        if (other.hasDefaultFee()) {
          setDefaultFee(other.getDefaultFee());
        }
        if (other.hasTOR()) {
          setTOR(other.getTOR());
        }
        if (other.hasConnectOnLocalHost()) {
          setConnectOnLocalHost(other.getConnectOnLocalHost());
        }
        if (other.hasConnectToTrustedPeer()) {
          setConnectToTrustedPeer(other.getConnectToTrustedPeer());
        }
        if (other.hasPortForwarding()) {
          setPortForwarding(other.getPortForwarding());
        }
        if (other.hasTrustedPeerIP()) {
          bitField0_ |= 0x00000200;
          trustedPeerIP_ = other.trustedPeerIP_;
          onChanged();
        }
        if (other.hasBloomFilterFalsePositiveRate()) {
          setBloomFilterFalsePositiveRate(other.getBloomFilterFalsePositiveRate());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.authenticator.protobuf.ProtoSettings.ConfigSettings parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.authenticator.protobuf.ProtoSettings.ConfigSettings) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private org.authenticator.protobuf.ProtoSettings.BitcoinUnit accountUnit_ = org.authenticator.protobuf.ProtoSettings.BitcoinUnit.BTC;
      /**
       * <code>optional .org.authenticator.protobuf.BitcoinUnit accountUnit = 1 [default = BTC];</code>
       */
      public boolean hasAccountUnit() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .org.authenticator.protobuf.BitcoinUnit accountUnit = 1 [default = BTC];</code>
       */
      public org.authenticator.protobuf.ProtoSettings.BitcoinUnit getAccountUnit() {
        return accountUnit_;
      }
      /**
       * <code>optional .org.authenticator.protobuf.BitcoinUnit accountUnit = 1 [default = BTC];</code>
       */
      public Builder setAccountUnit(org.authenticator.protobuf.ProtoSettings.BitcoinUnit value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        accountUnit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .org.authenticator.protobuf.BitcoinUnit accountUnit = 1 [default = BTC];</code>
       */
      public Builder clearAccountUnit() {
        bitField0_ = (bitField0_ & ~0x00000001);
        accountUnit_ = org.authenticator.protobuf.ProtoSettings.BitcoinUnit.BTC;
        onChanged();
        return this;
      }

      private int decimalPoints_ = 4;
      /**
       * <code>optional int32 decimalPoints = 2 [default = 4];</code>
       */
      public boolean hasDecimalPoints() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 decimalPoints = 2 [default = 4];</code>
       */
      public int getDecimalPoints() {
        return decimalPoints_;
      }
      /**
       * <code>optional int32 decimalPoints = 2 [default = 4];</code>
       */
      public Builder setDecimalPoints(int value) {
        bitField0_ |= 0x00000002;
        decimalPoints_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 decimalPoints = 2 [default = 4];</code>
       */
      public Builder clearDecimalPoints() {
        bitField0_ = (bitField0_ & ~0x00000002);
        decimalPoints_ = 4;
        onChanged();
        return this;
      }

      private java.lang.Object localCurrencySymbol_ = "USD";
      /**
       * <code>optional string localCurrencySymbol = 3 [default = "USD"];</code>
       */
      public boolean hasLocalCurrencySymbol() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string localCurrencySymbol = 3 [default = "USD"];</code>
       */
      public java.lang.String getLocalCurrencySymbol() {
        java.lang.Object ref = localCurrencySymbol_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            localCurrencySymbol_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string localCurrencySymbol = 3 [default = "USD"];</code>
       */
      public com.google.protobuf.ByteString
          getLocalCurrencySymbolBytes() {
        java.lang.Object ref = localCurrencySymbol_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          localCurrencySymbol_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string localCurrencySymbol = 3 [default = "USD"];</code>
       */
      public Builder setLocalCurrencySymbol(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        localCurrencySymbol_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string localCurrencySymbol = 3 [default = "USD"];</code>
       */
      public Builder clearLocalCurrencySymbol() {
        bitField0_ = (bitField0_ & ~0x00000004);
        localCurrencySymbol_ = getDefaultInstance().getLocalCurrencySymbol();
        onChanged();
        return this;
      }
      /**
       * <code>optional string localCurrencySymbol = 3 [default = "USD"];</code>
       */
      public Builder setLocalCurrencySymbolBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        localCurrencySymbol_ = value;
        onChanged();
        return this;
      }

      private org.authenticator.protobuf.ProtoSettings.Languages language_ = org.authenticator.protobuf.ProtoSettings.Languages.English;
      /**
       * <code>optional .org.authenticator.protobuf.Languages language = 4 [default = English];</code>
       */
      public boolean hasLanguage() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .org.authenticator.protobuf.Languages language = 4 [default = English];</code>
       */
      public org.authenticator.protobuf.ProtoSettings.Languages getLanguage() {
        return language_;
      }
      /**
       * <code>optional .org.authenticator.protobuf.Languages language = 4 [default = English];</code>
       */
      public Builder setLanguage(org.authenticator.protobuf.ProtoSettings.Languages value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        language_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .org.authenticator.protobuf.Languages language = 4 [default = English];</code>
       */
      public Builder clearLanguage() {
        bitField0_ = (bitField0_ & ~0x00000008);
        language_ = org.authenticator.protobuf.ProtoSettings.Languages.English;
        onChanged();
        return this;
      }

      private int defaultFee_ = 10000;
      /**
       * <code>optional int32 defaultFee = 5 [default = 10000];</code>
       *
       * <pre>
       * in satoshies
       * </pre>
       */
      public boolean hasDefaultFee() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 defaultFee = 5 [default = 10000];</code>
       *
       * <pre>
       * in satoshies
       * </pre>
       */
      public int getDefaultFee() {
        return defaultFee_;
      }
      /**
       * <code>optional int32 defaultFee = 5 [default = 10000];</code>
       *
       * <pre>
       * in satoshies
       * </pre>
       */
      public Builder setDefaultFee(int value) {
        bitField0_ |= 0x00000010;
        defaultFee_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 defaultFee = 5 [default = 10000];</code>
       *
       * <pre>
       * in satoshies
       * </pre>
       */
      public Builder clearDefaultFee() {
        bitField0_ = (bitField0_ & ~0x00000010);
        defaultFee_ = 10000;
        onChanged();
        return this;
      }

      private boolean tOR_ = true;
      /**
       * <code>optional bool TOR = 6 [default = true];</code>
       *
       * <pre>
       * flags
       * </pre>
       */
      public boolean hasTOR() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional bool TOR = 6 [default = true];</code>
       *
       * <pre>
       * flags
       * </pre>
       */
      public boolean getTOR() {
        return tOR_;
      }
      /**
       * <code>optional bool TOR = 6 [default = true];</code>
       *
       * <pre>
       * flags
       * </pre>
       */
      public Builder setTOR(boolean value) {
        bitField0_ |= 0x00000020;
        tOR_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool TOR = 6 [default = true];</code>
       *
       * <pre>
       * flags
       * </pre>
       */
      public Builder clearTOR() {
        bitField0_ = (bitField0_ & ~0x00000020);
        tOR_ = true;
        onChanged();
        return this;
      }

      private boolean connectOnLocalHost_ ;
      /**
       * <code>optional bool connectOnLocalHost = 7 [default = false];</code>
       */
      public boolean hasConnectOnLocalHost() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional bool connectOnLocalHost = 7 [default = false];</code>
       */
      public boolean getConnectOnLocalHost() {
        return connectOnLocalHost_;
      }
      /**
       * <code>optional bool connectOnLocalHost = 7 [default = false];</code>
       */
      public Builder setConnectOnLocalHost(boolean value) {
        bitField0_ |= 0x00000040;
        connectOnLocalHost_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool connectOnLocalHost = 7 [default = false];</code>
       */
      public Builder clearConnectOnLocalHost() {
        bitField0_ = (bitField0_ & ~0x00000040);
        connectOnLocalHost_ = false;
        onChanged();
        return this;
      }

      private boolean connectToTrustedPeer_ ;
      /**
       * <code>optional bool connectToTrustedPeer = 8 [default = false];</code>
       */
      public boolean hasConnectToTrustedPeer() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional bool connectToTrustedPeer = 8 [default = false];</code>
       */
      public boolean getConnectToTrustedPeer() {
        return connectToTrustedPeer_;
      }
      /**
       * <code>optional bool connectToTrustedPeer = 8 [default = false];</code>
       */
      public Builder setConnectToTrustedPeer(boolean value) {
        bitField0_ |= 0x00000080;
        connectToTrustedPeer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool connectToTrustedPeer = 8 [default = false];</code>
       */
      public Builder clearConnectToTrustedPeer() {
        bitField0_ = (bitField0_ & ~0x00000080);
        connectToTrustedPeer_ = false;
        onChanged();
        return this;
      }

      private boolean portForwarding_ ;
      /**
       * <code>optional bool portForwarding = 9 [default = false];</code>
       */
      public boolean hasPortForwarding() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional bool portForwarding = 9 [default = false];</code>
       */
      public boolean getPortForwarding() {
        return portForwarding_;
      }
      /**
       * <code>optional bool portForwarding = 9 [default = false];</code>
       */
      public Builder setPortForwarding(boolean value) {
        bitField0_ |= 0x00000100;
        portForwarding_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool portForwarding = 9 [default = false];</code>
       */
      public Builder clearPortForwarding() {
        bitField0_ = (bitField0_ & ~0x00000100);
        portForwarding_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object trustedPeerIP_ = "";
      /**
       * <code>optional string trustedPeerIP = 10;</code>
       */
      public boolean hasTrustedPeerIP() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional string trustedPeerIP = 10;</code>
       */
      public java.lang.String getTrustedPeerIP() {
        java.lang.Object ref = trustedPeerIP_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            trustedPeerIP_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string trustedPeerIP = 10;</code>
       */
      public com.google.protobuf.ByteString
          getTrustedPeerIPBytes() {
        java.lang.Object ref = trustedPeerIP_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          trustedPeerIP_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string trustedPeerIP = 10;</code>
       */
      public Builder setTrustedPeerIP(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        trustedPeerIP_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string trustedPeerIP = 10;</code>
       */
      public Builder clearTrustedPeerIP() {
        bitField0_ = (bitField0_ & ~0x00000200);
        trustedPeerIP_ = getDefaultInstance().getTrustedPeerIP();
        onChanged();
        return this;
      }
      /**
       * <code>optional string trustedPeerIP = 10;</code>
       */
      public Builder setTrustedPeerIPBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        trustedPeerIP_ = value;
        onChanged();
        return this;
      }

      private float bloomFilterFalsePositiveRate_ = 1e-05F;
      /**
       * <code>optional float bloomFilterFalsePositiveRate = 11 [default = 1e-05];</code>
       */
      public boolean hasBloomFilterFalsePositiveRate() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional float bloomFilterFalsePositiveRate = 11 [default = 1e-05];</code>
       */
      public float getBloomFilterFalsePositiveRate() {
        return bloomFilterFalsePositiveRate_;
      }
      /**
       * <code>optional float bloomFilterFalsePositiveRate = 11 [default = 1e-05];</code>
       */
      public Builder setBloomFilterFalsePositiveRate(float value) {
        bitField0_ |= 0x00000400;
        bloomFilterFalsePositiveRate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float bloomFilterFalsePositiveRate = 11 [default = 1e-05];</code>
       */
      public Builder clearBloomFilterFalsePositiveRate() {
        bitField0_ = (bitField0_ & ~0x00000400);
        bloomFilterFalsePositiveRate_ = 1e-05F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.authenticator.protobuf.ConfigSettings)
    }

    static {
      defaultInstance = new ConfigSettings(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.authenticator.protobuf.ConfigSettings)
  }

  public static final int BITCOIN_UNIT_NAME_FIELD_NUMBER = 50000;
  /**
   * <code>extend .google.protobuf.EnumValueOptions { ... }</code>
   *
   * <pre>
   * Be sure to read the docs about choosing the number here.
   * </pre>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.EnumValueOptions,
      java.lang.String> bitcoinUnitName = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_authenticator_protobuf_ConfigSettings_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_authenticator_protobuf_ConfigSettings_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024configSettings.proto\022\032org.authenticato" +
      "r.protobuf\032 google/protobuf/descriptor.p" +
      "roto\"\252\003\n\016ConfigSettings\022A\n\013accountUnit\030\001" +
      " \001(\0162\'.org.authenticator.protobuf.Bitcoi" +
      "nUnit:\003BTC\022\030\n\rdecimalPoints\030\002 \001(\005:\0014\022 \n\023" +
      "localCurrencySymbol\030\003 \001(\t:\003USD\022@\n\010langua" +
      "ge\030\004 \001(\0162%.org.authenticator.protobuf.La" +
      "nguages:\007English\022\031\n\ndefaultFee\030\005 \001(\005:\00510" +
      "000\022\021\n\003TOR\030\006 \001(\010:\004true\022!\n\022connectOnLocal" +
      "Host\030\007 \001(\010:\005false\022#\n\024connectToTrustedPee",
      "r\030\010 \001(\010:\005false\022\035\n\016portForwarding\030\t \001(\010:\005" +
      "false\022\025\n\rtrustedPeerIP\030\n \001(\t\022+\n\034bloomFil" +
      "terFalsePositiveRate\030\013 \001(\002:\0051e-05*R\n\013Bit" +
      "coinUnit\022\020\n\003BTC\020\000\032\007\202\265\030\003BTC\022\027\n\tMillibits\020" +
      "\001\032\010\202\265\030\004mBTC\022\030\n\tMicrobits\020\002\032\t\202\265\030\005\302\265BTC*\030\n" +
      "\tLanguages\022\013\n\007English\020\000:>\n\021bitcoin_unit_" +
      "name\022!.google.protobuf.EnumValueOptions\030" +
      "\320\206\003 \001(\tB\017B\rProtoSettings"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        }, assigner);
    internal_static_org_authenticator_protobuf_ConfigSettings_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_authenticator_protobuf_ConfigSettings_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_authenticator_protobuf_ConfigSettings_descriptor,
        new java.lang.String[] { "AccountUnit", "DecimalPoints", "LocalCurrencySymbol", "Language", "DefaultFee", "TOR", "ConnectOnLocalHost", "ConnectToTrustedPeer", "PortForwarding", "TrustedPeerIP", "BloomFilterFalsePositiveRate", });
    bitcoinUnitName.internalInit(descriptor.getExtensions().get(0));
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(org.authenticator.protobuf.ProtoSettings.bitcoinUnitName);
    registry.add(org.authenticator.protobuf.ProtoSettings.bitcoinUnitName);
    registry.add(org.authenticator.protobuf.ProtoSettings.bitcoinUnitName);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
