// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: configSettings.proto

package authenticator.protobuf;

public final class ProtoSettings {
  private ProtoSettings() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code authenticator.protobuf.BitcoinUnit}
   */
  public enum BitcoinUnit
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>BTC = 0;</code>
     */
    BTC(0, 0),
    /**
     * <code>Bits = 1;</code>
     */
    Bits(1, 1),
    /**
     * <code>Millibits = 2;</code>
     */
    Millibits(2, 2),
    /**
     * <code>NanoBits = 3;</code>
     */
    NanoBits(3, 3),
    ;

    /**
     * <code>BTC = 0;</code>
     */
    public static final int BTC_VALUE = 0;
    /**
     * <code>Bits = 1;</code>
     */
    public static final int Bits_VALUE = 1;
    /**
     * <code>Millibits = 2;</code>
     */
    public static final int Millibits_VALUE = 2;
    /**
     * <code>NanoBits = 3;</code>
     */
    public static final int NanoBits_VALUE = 3;


    public final int getNumber() { return value; }

    public static BitcoinUnit valueOf(int value) {
      switch (value) {
        case 0: return BTC;
        case 1: return Bits;
        case 2: return Millibits;
        case 3: return NanoBits;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<BitcoinUnit>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<BitcoinUnit>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<BitcoinUnit>() {
            public BitcoinUnit findValueByNumber(int number) {
              return BitcoinUnit.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return authenticator.protobuf.ProtoSettings.getDescriptor().getEnumTypes().get(0);
    }

    private static final BitcoinUnit[] VALUES = values();

    public static BitcoinUnit valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private BitcoinUnit(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:authenticator.protobuf.BitcoinUnit)
  }

  /**
   * Protobuf enum {@code authenticator.protobuf.Languages}
   */
  public enum Languages
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>English = 0;</code>
     */
    English(0, 0),
    ;

    /**
     * <code>English = 0;</code>
     */
    public static final int English_VALUE = 0;


    public final int getNumber() { return value; }

    public static Languages valueOf(int value) {
      switch (value) {
        case 0: return English;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Languages>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Languages>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Languages>() {
            public Languages findValueByNumber(int number) {
              return Languages.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return authenticator.protobuf.ProtoSettings.getDescriptor().getEnumTypes().get(1);
    }

    private static final Languages[] VALUES = values();

    public static Languages valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Languages(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:authenticator.protobuf.Languages)
  }

  public interface ConfigSettingsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .authenticator.protobuf.BitcoinUnit accountUnit = 1 [default = Bits];
    /**
     * <code>optional .authenticator.protobuf.BitcoinUnit accountUnit = 1 [default = Bits];</code>
     */
    boolean hasAccountUnit();
    /**
     * <code>optional .authenticator.protobuf.BitcoinUnit accountUnit = 1 [default = Bits];</code>
     */
    authenticator.protobuf.ProtoSettings.BitcoinUnit getAccountUnit();

    // optional int32 decimalPoints = 2 [default = 2];
    /**
     * <code>optional int32 decimalPoints = 2 [default = 2];</code>
     */
    boolean hasDecimalPoints();
    /**
     * <code>optional int32 decimalPoints = 2 [default = 2];</code>
     */
    int getDecimalPoints();

    // optional string localCurrencySymbol = 3 [default = "USD"];
    /**
     * <code>optional string localCurrencySymbol = 3 [default = "USD"];</code>
     */
    boolean hasLocalCurrencySymbol();
    /**
     * <code>optional string localCurrencySymbol = 3 [default = "USD"];</code>
     */
    java.lang.String getLocalCurrencySymbol();
    /**
     * <code>optional string localCurrencySymbol = 3 [default = "USD"];</code>
     */
    com.google.protobuf.ByteString
        getLocalCurrencySymbolBytes();

    // optional .authenticator.protobuf.Languages language = 4 [default = English];
    /**
     * <code>optional .authenticator.protobuf.Languages language = 4 [default = English];</code>
     */
    boolean hasLanguage();
    /**
     * <code>optional .authenticator.protobuf.Languages language = 4 [default = English];</code>
     */
    authenticator.protobuf.ProtoSettings.Languages getLanguage();

    // optional int32 defaultFee = 5 [default = 10000];
    /**
     * <code>optional int32 defaultFee = 5 [default = 10000];</code>
     *
     * <pre>
     * in satoshies
     * </pre>
     */
    boolean hasDefaultFee();
    /**
     * <code>optional int32 defaultFee = 5 [default = 10000];</code>
     *
     * <pre>
     * in satoshies
     * </pre>
     */
    int getDefaultFee();

    // optional bool TOR = 6 [default = true];
    /**
     * <code>optional bool TOR = 6 [default = true];</code>
     *
     * <pre>
     * flags
     * </pre>
     */
    boolean hasTOR();
    /**
     * <code>optional bool TOR = 6 [default = true];</code>
     *
     * <pre>
     * flags
     * </pre>
     */
    boolean getTOR();

    // optional bool connectOnLocalHost = 7 [default = false];
    /**
     * <code>optional bool connectOnLocalHost = 7 [default = false];</code>
     */
    boolean hasConnectOnLocalHost();
    /**
     * <code>optional bool connectOnLocalHost = 7 [default = false];</code>
     */
    boolean getConnectOnLocalHost();

    // optional bool connectToTrustedPeer = 8 [default = false];
    /**
     * <code>optional bool connectToTrustedPeer = 8 [default = false];</code>
     */
    boolean hasConnectToTrustedPeer();
    /**
     * <code>optional bool connectToTrustedPeer = 8 [default = false];</code>
     */
    boolean getConnectToTrustedPeer();

    // optional string trustedPeerIP = 9;
    /**
     * <code>optional string trustedPeerIP = 9;</code>
     */
    boolean hasTrustedPeerIP();
    /**
     * <code>optional string trustedPeerIP = 9;</code>
     */
    java.lang.String getTrustedPeerIP();
    /**
     * <code>optional string trustedPeerIP = 9;</code>
     */
    com.google.protobuf.ByteString
        getTrustedPeerIPBytes();

    // optional float bloomFilterFalsePositiveRate = 10 [default = 0.0005];
    /**
     * <code>optional float bloomFilterFalsePositiveRate = 10 [default = 0.0005];</code>
     */
    boolean hasBloomFilterFalsePositiveRate();
    /**
     * <code>optional float bloomFilterFalsePositiveRate = 10 [default = 0.0005];</code>
     */
    float getBloomFilterFalsePositiveRate();
  }
  /**
   * Protobuf type {@code authenticator.protobuf.ConfigSettings}
   */
  public static final class ConfigSettings extends
      com.google.protobuf.GeneratedMessage
      implements ConfigSettingsOrBuilder {
    // Use ConfigSettings.newBuilder() to construct.
    private ConfigSettings(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ConfigSettings(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ConfigSettings defaultInstance;
    public static ConfigSettings getDefaultInstance() {
      return defaultInstance;
    }

    public ConfigSettings getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ConfigSettings(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              authenticator.protobuf.ProtoSettings.BitcoinUnit value = authenticator.protobuf.ProtoSettings.BitcoinUnit.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                accountUnit_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              decimalPoints_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              localCurrencySymbol_ = input.readBytes();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              authenticator.protobuf.ProtoSettings.Languages value = authenticator.protobuf.ProtoSettings.Languages.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                language_ = value;
              }
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              defaultFee_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              tOR_ = input.readBool();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              connectOnLocalHost_ = input.readBool();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              connectToTrustedPeer_ = input.readBool();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              trustedPeerIP_ = input.readBytes();
              break;
            }
            case 85: {
              bitField0_ |= 0x00000200;
              bloomFilterFalsePositiveRate_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return authenticator.protobuf.ProtoSettings.internal_static_authenticator_protobuf_ConfigSettings_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return authenticator.protobuf.ProtoSettings.internal_static_authenticator_protobuf_ConfigSettings_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              authenticator.protobuf.ProtoSettings.ConfigSettings.class, authenticator.protobuf.ProtoSettings.ConfigSettings.Builder.class);
    }

    public static com.google.protobuf.Parser<ConfigSettings> PARSER =
        new com.google.protobuf.AbstractParser<ConfigSettings>() {
      public ConfigSettings parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConfigSettings(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ConfigSettings> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .authenticator.protobuf.BitcoinUnit accountUnit = 1 [default = Bits];
    public static final int ACCOUNTUNIT_FIELD_NUMBER = 1;
    private authenticator.protobuf.ProtoSettings.BitcoinUnit accountUnit_;
    /**
     * <code>optional .authenticator.protobuf.BitcoinUnit accountUnit = 1 [default = Bits];</code>
     */
    public boolean hasAccountUnit() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .authenticator.protobuf.BitcoinUnit accountUnit = 1 [default = Bits];</code>
     */
    public authenticator.protobuf.ProtoSettings.BitcoinUnit getAccountUnit() {
      return accountUnit_;
    }

    // optional int32 decimalPoints = 2 [default = 2];
    public static final int DECIMALPOINTS_FIELD_NUMBER = 2;
    private int decimalPoints_;
    /**
     * <code>optional int32 decimalPoints = 2 [default = 2];</code>
     */
    public boolean hasDecimalPoints() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 decimalPoints = 2 [default = 2];</code>
     */
    public int getDecimalPoints() {
      return decimalPoints_;
    }

    // optional string localCurrencySymbol = 3 [default = "USD"];
    public static final int LOCALCURRENCYSYMBOL_FIELD_NUMBER = 3;
    private java.lang.Object localCurrencySymbol_;
    /**
     * <code>optional string localCurrencySymbol = 3 [default = "USD"];</code>
     */
    public boolean hasLocalCurrencySymbol() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string localCurrencySymbol = 3 [default = "USD"];</code>
     */
    public java.lang.String getLocalCurrencySymbol() {
      java.lang.Object ref = localCurrencySymbol_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          localCurrencySymbol_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string localCurrencySymbol = 3 [default = "USD"];</code>
     */
    public com.google.protobuf.ByteString
        getLocalCurrencySymbolBytes() {
      java.lang.Object ref = localCurrencySymbol_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        localCurrencySymbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional .authenticator.protobuf.Languages language = 4 [default = English];
    public static final int LANGUAGE_FIELD_NUMBER = 4;
    private authenticator.protobuf.ProtoSettings.Languages language_;
    /**
     * <code>optional .authenticator.protobuf.Languages language = 4 [default = English];</code>
     */
    public boolean hasLanguage() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .authenticator.protobuf.Languages language = 4 [default = English];</code>
     */
    public authenticator.protobuf.ProtoSettings.Languages getLanguage() {
      return language_;
    }

    // optional int32 defaultFee = 5 [default = 10000];
    public static final int DEFAULTFEE_FIELD_NUMBER = 5;
    private int defaultFee_;
    /**
     * <code>optional int32 defaultFee = 5 [default = 10000];</code>
     *
     * <pre>
     * in satoshies
     * </pre>
     */
    public boolean hasDefaultFee() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 defaultFee = 5 [default = 10000];</code>
     *
     * <pre>
     * in satoshies
     * </pre>
     */
    public int getDefaultFee() {
      return defaultFee_;
    }

    // optional bool TOR = 6 [default = true];
    public static final int TOR_FIELD_NUMBER = 6;
    private boolean tOR_;
    /**
     * <code>optional bool TOR = 6 [default = true];</code>
     *
     * <pre>
     * flags
     * </pre>
     */
    public boolean hasTOR() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional bool TOR = 6 [default = true];</code>
     *
     * <pre>
     * flags
     * </pre>
     */
    public boolean getTOR() {
      return tOR_;
    }

    // optional bool connectOnLocalHost = 7 [default = false];
    public static final int CONNECTONLOCALHOST_FIELD_NUMBER = 7;
    private boolean connectOnLocalHost_;
    /**
     * <code>optional bool connectOnLocalHost = 7 [default = false];</code>
     */
    public boolean hasConnectOnLocalHost() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional bool connectOnLocalHost = 7 [default = false];</code>
     */
    public boolean getConnectOnLocalHost() {
      return connectOnLocalHost_;
    }

    // optional bool connectToTrustedPeer = 8 [default = false];
    public static final int CONNECTTOTRUSTEDPEER_FIELD_NUMBER = 8;
    private boolean connectToTrustedPeer_;
    /**
     * <code>optional bool connectToTrustedPeer = 8 [default = false];</code>
     */
    public boolean hasConnectToTrustedPeer() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional bool connectToTrustedPeer = 8 [default = false];</code>
     */
    public boolean getConnectToTrustedPeer() {
      return connectToTrustedPeer_;
    }

    // optional string trustedPeerIP = 9;
    public static final int TRUSTEDPEERIP_FIELD_NUMBER = 9;
    private java.lang.Object trustedPeerIP_;
    /**
     * <code>optional string trustedPeerIP = 9;</code>
     */
    public boolean hasTrustedPeerIP() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string trustedPeerIP = 9;</code>
     */
    public java.lang.String getTrustedPeerIP() {
      java.lang.Object ref = trustedPeerIP_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          trustedPeerIP_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string trustedPeerIP = 9;</code>
     */
    public com.google.protobuf.ByteString
        getTrustedPeerIPBytes() {
      java.lang.Object ref = trustedPeerIP_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        trustedPeerIP_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional float bloomFilterFalsePositiveRate = 10 [default = 0.0005];
    public static final int BLOOMFILTERFALSEPOSITIVERATE_FIELD_NUMBER = 10;
    private float bloomFilterFalsePositiveRate_;
    /**
     * <code>optional float bloomFilterFalsePositiveRate = 10 [default = 0.0005];</code>
     */
    public boolean hasBloomFilterFalsePositiveRate() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional float bloomFilterFalsePositiveRate = 10 [default = 0.0005];</code>
     */
    public float getBloomFilterFalsePositiveRate() {
      return bloomFilterFalsePositiveRate_;
    }

    private void initFields() {
      accountUnit_ = authenticator.protobuf.ProtoSettings.BitcoinUnit.Bits;
      decimalPoints_ = 2;
      localCurrencySymbol_ = "USD";
      language_ = authenticator.protobuf.ProtoSettings.Languages.English;
      defaultFee_ = 10000;
      tOR_ = true;
      connectOnLocalHost_ = false;
      connectToTrustedPeer_ = false;
      trustedPeerIP_ = "";
      bloomFilterFalsePositiveRate_ = 0.0005F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, accountUnit_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, decimalPoints_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getLocalCurrencySymbolBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, language_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, defaultFee_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBool(6, tOR_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBool(7, connectOnLocalHost_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBool(8, connectToTrustedPeer_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getTrustedPeerIPBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeFloat(10, bloomFilterFalsePositiveRate_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, accountUnit_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, decimalPoints_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getLocalCurrencySymbolBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, language_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, defaultFee_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, tOR_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, connectOnLocalHost_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, connectToTrustedPeer_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getTrustedPeerIPBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(10, bloomFilterFalsePositiveRate_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static authenticator.protobuf.ProtoSettings.ConfigSettings parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static authenticator.protobuf.ProtoSettings.ConfigSettings parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static authenticator.protobuf.ProtoSettings.ConfigSettings parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static authenticator.protobuf.ProtoSettings.ConfigSettings parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static authenticator.protobuf.ProtoSettings.ConfigSettings parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static authenticator.protobuf.ProtoSettings.ConfigSettings parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static authenticator.protobuf.ProtoSettings.ConfigSettings parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static authenticator.protobuf.ProtoSettings.ConfigSettings parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static authenticator.protobuf.ProtoSettings.ConfigSettings parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static authenticator.protobuf.ProtoSettings.ConfigSettings parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(authenticator.protobuf.ProtoSettings.ConfigSettings prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code authenticator.protobuf.ConfigSettings}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements authenticator.protobuf.ProtoSettings.ConfigSettingsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return authenticator.protobuf.ProtoSettings.internal_static_authenticator_protobuf_ConfigSettings_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return authenticator.protobuf.ProtoSettings.internal_static_authenticator_protobuf_ConfigSettings_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                authenticator.protobuf.ProtoSettings.ConfigSettings.class, authenticator.protobuf.ProtoSettings.ConfigSettings.Builder.class);
      }

      // Construct using authenticator.protobuf.ProtoSettings.ConfigSettings.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        accountUnit_ = authenticator.protobuf.ProtoSettings.BitcoinUnit.Bits;
        bitField0_ = (bitField0_ & ~0x00000001);
        decimalPoints_ = 2;
        bitField0_ = (bitField0_ & ~0x00000002);
        localCurrencySymbol_ = "USD";
        bitField0_ = (bitField0_ & ~0x00000004);
        language_ = authenticator.protobuf.ProtoSettings.Languages.English;
        bitField0_ = (bitField0_ & ~0x00000008);
        defaultFee_ = 10000;
        bitField0_ = (bitField0_ & ~0x00000010);
        tOR_ = true;
        bitField0_ = (bitField0_ & ~0x00000020);
        connectOnLocalHost_ = false;
        bitField0_ = (bitField0_ & ~0x00000040);
        connectToTrustedPeer_ = false;
        bitField0_ = (bitField0_ & ~0x00000080);
        trustedPeerIP_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        bloomFilterFalsePositiveRate_ = 0.0005F;
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return authenticator.protobuf.ProtoSettings.internal_static_authenticator_protobuf_ConfigSettings_descriptor;
      }

      public authenticator.protobuf.ProtoSettings.ConfigSettings getDefaultInstanceForType() {
        return authenticator.protobuf.ProtoSettings.ConfigSettings.getDefaultInstance();
      }

      public authenticator.protobuf.ProtoSettings.ConfigSettings build() {
        authenticator.protobuf.ProtoSettings.ConfigSettings result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public authenticator.protobuf.ProtoSettings.ConfigSettings buildPartial() {
        authenticator.protobuf.ProtoSettings.ConfigSettings result = new authenticator.protobuf.ProtoSettings.ConfigSettings(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.accountUnit_ = accountUnit_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.decimalPoints_ = decimalPoints_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.localCurrencySymbol_ = localCurrencySymbol_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.language_ = language_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.defaultFee_ = defaultFee_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.tOR_ = tOR_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.connectOnLocalHost_ = connectOnLocalHost_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.connectToTrustedPeer_ = connectToTrustedPeer_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.trustedPeerIP_ = trustedPeerIP_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.bloomFilterFalsePositiveRate_ = bloomFilterFalsePositiveRate_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof authenticator.protobuf.ProtoSettings.ConfigSettings) {
          return mergeFrom((authenticator.protobuf.ProtoSettings.ConfigSettings)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(authenticator.protobuf.ProtoSettings.ConfigSettings other) {
        if (other == authenticator.protobuf.ProtoSettings.ConfigSettings.getDefaultInstance()) return this;
        if (other.hasAccountUnit()) {
          setAccountUnit(other.getAccountUnit());
        }
        if (other.hasDecimalPoints()) {
          setDecimalPoints(other.getDecimalPoints());
        }
        if (other.hasLocalCurrencySymbol()) {
          bitField0_ |= 0x00000004;
          localCurrencySymbol_ = other.localCurrencySymbol_;
          onChanged();
        }
        if (other.hasLanguage()) {
          setLanguage(other.getLanguage());
        }
        if (other.hasDefaultFee()) {
          setDefaultFee(other.getDefaultFee());
        }
        if (other.hasTOR()) {
          setTOR(other.getTOR());
        }
        if (other.hasConnectOnLocalHost()) {
          setConnectOnLocalHost(other.getConnectOnLocalHost());
        }
        if (other.hasConnectToTrustedPeer()) {
          setConnectToTrustedPeer(other.getConnectToTrustedPeer());
        }
        if (other.hasTrustedPeerIP()) {
          bitField0_ |= 0x00000100;
          trustedPeerIP_ = other.trustedPeerIP_;
          onChanged();
        }
        if (other.hasBloomFilterFalsePositiveRate()) {
          setBloomFilterFalsePositiveRate(other.getBloomFilterFalsePositiveRate());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        authenticator.protobuf.ProtoSettings.ConfigSettings parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (authenticator.protobuf.ProtoSettings.ConfigSettings) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .authenticator.protobuf.BitcoinUnit accountUnit = 1 [default = Bits];
      private authenticator.protobuf.ProtoSettings.BitcoinUnit accountUnit_ = authenticator.protobuf.ProtoSettings.BitcoinUnit.Bits;
      /**
       * <code>optional .authenticator.protobuf.BitcoinUnit accountUnit = 1 [default = Bits];</code>
       */
      public boolean hasAccountUnit() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .authenticator.protobuf.BitcoinUnit accountUnit = 1 [default = Bits];</code>
       */
      public authenticator.protobuf.ProtoSettings.BitcoinUnit getAccountUnit() {
        return accountUnit_;
      }
      /**
       * <code>optional .authenticator.protobuf.BitcoinUnit accountUnit = 1 [default = Bits];</code>
       */
      public Builder setAccountUnit(authenticator.protobuf.ProtoSettings.BitcoinUnit value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        accountUnit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .authenticator.protobuf.BitcoinUnit accountUnit = 1 [default = Bits];</code>
       */
      public Builder clearAccountUnit() {
        bitField0_ = (bitField0_ & ~0x00000001);
        accountUnit_ = authenticator.protobuf.ProtoSettings.BitcoinUnit.Bits;
        onChanged();
        return this;
      }

      // optional int32 decimalPoints = 2 [default = 2];
      private int decimalPoints_ = 2;
      /**
       * <code>optional int32 decimalPoints = 2 [default = 2];</code>
       */
      public boolean hasDecimalPoints() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 decimalPoints = 2 [default = 2];</code>
       */
      public int getDecimalPoints() {
        return decimalPoints_;
      }
      /**
       * <code>optional int32 decimalPoints = 2 [default = 2];</code>
       */
      public Builder setDecimalPoints(int value) {
        bitField0_ |= 0x00000002;
        decimalPoints_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 decimalPoints = 2 [default = 2];</code>
       */
      public Builder clearDecimalPoints() {
        bitField0_ = (bitField0_ & ~0x00000002);
        decimalPoints_ = 2;
        onChanged();
        return this;
      }

      // optional string localCurrencySymbol = 3 [default = "USD"];
      private java.lang.Object localCurrencySymbol_ = "USD";
      /**
       * <code>optional string localCurrencySymbol = 3 [default = "USD"];</code>
       */
      public boolean hasLocalCurrencySymbol() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string localCurrencySymbol = 3 [default = "USD"];</code>
       */
      public java.lang.String getLocalCurrencySymbol() {
        java.lang.Object ref = localCurrencySymbol_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          localCurrencySymbol_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string localCurrencySymbol = 3 [default = "USD"];</code>
       */
      public com.google.protobuf.ByteString
          getLocalCurrencySymbolBytes() {
        java.lang.Object ref = localCurrencySymbol_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          localCurrencySymbol_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string localCurrencySymbol = 3 [default = "USD"];</code>
       */
      public Builder setLocalCurrencySymbol(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        localCurrencySymbol_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string localCurrencySymbol = 3 [default = "USD"];</code>
       */
      public Builder clearLocalCurrencySymbol() {
        bitField0_ = (bitField0_ & ~0x00000004);
        localCurrencySymbol_ = getDefaultInstance().getLocalCurrencySymbol();
        onChanged();
        return this;
      }
      /**
       * <code>optional string localCurrencySymbol = 3 [default = "USD"];</code>
       */
      public Builder setLocalCurrencySymbolBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        localCurrencySymbol_ = value;
        onChanged();
        return this;
      }

      // optional .authenticator.protobuf.Languages language = 4 [default = English];
      private authenticator.protobuf.ProtoSettings.Languages language_ = authenticator.protobuf.ProtoSettings.Languages.English;
      /**
       * <code>optional .authenticator.protobuf.Languages language = 4 [default = English];</code>
       */
      public boolean hasLanguage() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .authenticator.protobuf.Languages language = 4 [default = English];</code>
       */
      public authenticator.protobuf.ProtoSettings.Languages getLanguage() {
        return language_;
      }
      /**
       * <code>optional .authenticator.protobuf.Languages language = 4 [default = English];</code>
       */
      public Builder setLanguage(authenticator.protobuf.ProtoSettings.Languages value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        language_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .authenticator.protobuf.Languages language = 4 [default = English];</code>
       */
      public Builder clearLanguage() {
        bitField0_ = (bitField0_ & ~0x00000008);
        language_ = authenticator.protobuf.ProtoSettings.Languages.English;
        onChanged();
        return this;
      }

      // optional int32 defaultFee = 5 [default = 10000];
      private int defaultFee_ = 10000;
      /**
       * <code>optional int32 defaultFee = 5 [default = 10000];</code>
       *
       * <pre>
       * in satoshies
       * </pre>
       */
      public boolean hasDefaultFee() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 defaultFee = 5 [default = 10000];</code>
       *
       * <pre>
       * in satoshies
       * </pre>
       */
      public int getDefaultFee() {
        return defaultFee_;
      }
      /**
       * <code>optional int32 defaultFee = 5 [default = 10000];</code>
       *
       * <pre>
       * in satoshies
       * </pre>
       */
      public Builder setDefaultFee(int value) {
        bitField0_ |= 0x00000010;
        defaultFee_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 defaultFee = 5 [default = 10000];</code>
       *
       * <pre>
       * in satoshies
       * </pre>
       */
      public Builder clearDefaultFee() {
        bitField0_ = (bitField0_ & ~0x00000010);
        defaultFee_ = 10000;
        onChanged();
        return this;
      }

      // optional bool TOR = 6 [default = true];
      private boolean tOR_ = true;
      /**
       * <code>optional bool TOR = 6 [default = true];</code>
       *
       * <pre>
       * flags
       * </pre>
       */
      public boolean hasTOR() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional bool TOR = 6 [default = true];</code>
       *
       * <pre>
       * flags
       * </pre>
       */
      public boolean getTOR() {
        return tOR_;
      }
      /**
       * <code>optional bool TOR = 6 [default = true];</code>
       *
       * <pre>
       * flags
       * </pre>
       */
      public Builder setTOR(boolean value) {
        bitField0_ |= 0x00000020;
        tOR_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool TOR = 6 [default = true];</code>
       *
       * <pre>
       * flags
       * </pre>
       */
      public Builder clearTOR() {
        bitField0_ = (bitField0_ & ~0x00000020);
        tOR_ = true;
        onChanged();
        return this;
      }

      // optional bool connectOnLocalHost = 7 [default = false];
      private boolean connectOnLocalHost_ ;
      /**
       * <code>optional bool connectOnLocalHost = 7 [default = false];</code>
       */
      public boolean hasConnectOnLocalHost() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional bool connectOnLocalHost = 7 [default = false];</code>
       */
      public boolean getConnectOnLocalHost() {
        return connectOnLocalHost_;
      }
      /**
       * <code>optional bool connectOnLocalHost = 7 [default = false];</code>
       */
      public Builder setConnectOnLocalHost(boolean value) {
        bitField0_ |= 0x00000040;
        connectOnLocalHost_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool connectOnLocalHost = 7 [default = false];</code>
       */
      public Builder clearConnectOnLocalHost() {
        bitField0_ = (bitField0_ & ~0x00000040);
        connectOnLocalHost_ = false;
        onChanged();
        return this;
      }

      // optional bool connectToTrustedPeer = 8 [default = false];
      private boolean connectToTrustedPeer_ ;
      /**
       * <code>optional bool connectToTrustedPeer = 8 [default = false];</code>
       */
      public boolean hasConnectToTrustedPeer() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional bool connectToTrustedPeer = 8 [default = false];</code>
       */
      public boolean getConnectToTrustedPeer() {
        return connectToTrustedPeer_;
      }
      /**
       * <code>optional bool connectToTrustedPeer = 8 [default = false];</code>
       */
      public Builder setConnectToTrustedPeer(boolean value) {
        bitField0_ |= 0x00000080;
        connectToTrustedPeer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool connectToTrustedPeer = 8 [default = false];</code>
       */
      public Builder clearConnectToTrustedPeer() {
        bitField0_ = (bitField0_ & ~0x00000080);
        connectToTrustedPeer_ = false;
        onChanged();
        return this;
      }

      // optional string trustedPeerIP = 9;
      private java.lang.Object trustedPeerIP_ = "";
      /**
       * <code>optional string trustedPeerIP = 9;</code>
       */
      public boolean hasTrustedPeerIP() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string trustedPeerIP = 9;</code>
       */
      public java.lang.String getTrustedPeerIP() {
        java.lang.Object ref = trustedPeerIP_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          trustedPeerIP_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string trustedPeerIP = 9;</code>
       */
      public com.google.protobuf.ByteString
          getTrustedPeerIPBytes() {
        java.lang.Object ref = trustedPeerIP_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          trustedPeerIP_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string trustedPeerIP = 9;</code>
       */
      public Builder setTrustedPeerIP(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        trustedPeerIP_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string trustedPeerIP = 9;</code>
       */
      public Builder clearTrustedPeerIP() {
        bitField0_ = (bitField0_ & ~0x00000100);
        trustedPeerIP_ = getDefaultInstance().getTrustedPeerIP();
        onChanged();
        return this;
      }
      /**
       * <code>optional string trustedPeerIP = 9;</code>
       */
      public Builder setTrustedPeerIPBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        trustedPeerIP_ = value;
        onChanged();
        return this;
      }

      // optional float bloomFilterFalsePositiveRate = 10 [default = 0.0005];
      private float bloomFilterFalsePositiveRate_ = 0.0005F;
      /**
       * <code>optional float bloomFilterFalsePositiveRate = 10 [default = 0.0005];</code>
       */
      public boolean hasBloomFilterFalsePositiveRate() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional float bloomFilterFalsePositiveRate = 10 [default = 0.0005];</code>
       */
      public float getBloomFilterFalsePositiveRate() {
        return bloomFilterFalsePositiveRate_;
      }
      /**
       * <code>optional float bloomFilterFalsePositiveRate = 10 [default = 0.0005];</code>
       */
      public Builder setBloomFilterFalsePositiveRate(float value) {
        bitField0_ |= 0x00000200;
        bloomFilterFalsePositiveRate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float bloomFilterFalsePositiveRate = 10 [default = 0.0005];</code>
       */
      public Builder clearBloomFilterFalsePositiveRate() {
        bitField0_ = (bitField0_ & ~0x00000200);
        bloomFilterFalsePositiveRate_ = 0.0005F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:authenticator.protobuf.ConfigSettings)
    }

    static {
      defaultInstance = new ConfigSettings(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:authenticator.protobuf.ConfigSettings)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_authenticator_protobuf_ConfigSettings_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_authenticator_protobuf_ConfigSettings_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024configSettings.proto\022\026authenticator.pr" +
      "otobuf\"\205\003\n\016ConfigSettings\022>\n\013accountUnit" +
      "\030\001 \001(\0162#.authenticator.protobuf.BitcoinU" +
      "nit:\004Bits\022\030\n\rdecimalPoints\030\002 \001(\005:\0012\022 \n\023l" +
      "ocalCurrencySymbol\030\003 \001(\t:\003USD\022<\n\010languag" +
      "e\030\004 \001(\0162!.authenticator.protobuf.Languag" +
      "es:\007English\022\031\n\ndefaultFee\030\005 \001(\005:\00510000\022\021" +
      "\n\003TOR\030\006 \001(\010:\004true\022!\n\022connectOnLocalHost\030" +
      "\007 \001(\010:\005false\022#\n\024connectToTrustedPeer\030\010 \001" +
      "(\010:\005false\022\025\n\rtrustedPeerIP\030\t \001(\t\022,\n\034bloo",
      "mFilterFalsePositiveRate\030\n \001(\002:\0060.0005*=" +
      "\n\013BitcoinUnit\022\007\n\003BTC\020\000\022\010\n\004Bits\020\001\022\r\n\tMill" +
      "ibits\020\002\022\014\n\010NanoBits\020\003*\030\n\tLanguages\022\013\n\007En" +
      "glish\020\000B\017B\rProtoSettings"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_authenticator_protobuf_ConfigSettings_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_authenticator_protobuf_ConfigSettings_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_authenticator_protobuf_ConfigSettings_descriptor,
              new java.lang.String[] { "AccountUnit", "DecimalPoints", "LocalCurrencySymbol", "Language", "DefaultFee", "TOR", "ConnectOnLocalHost", "ConnectToTrustedPeer", "TrustedPeerIP", "BloomFilterFalsePositiveRate", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
